### ISSUE TITLE
Document how to change adapter options

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#10]
PHP adapter supports options like `port`, `pathMappings` and others but it's not clear to me how to configure them. I would need to dig deep into source code to see if that's even possible.

**Comment by slifin** [comment]
This doesn't directly address your issue (request for documentation) but add 
```
"debug.configurations": [
        {
            "name": "xdebug",
            "type":"php",
            "request": "launch",
            "port": 9000,
            "pathMappings" : (whatever vscode's extension does here)
        }
    ]
```
inside your project settings file, (make sure this is inside the settings key or it won't work)

related issue: https://github.com/daveleroy/sublime_db/issues/5

**Comment by AmjadHD** [comment]
more generally, I think there should be a description in the docs for the general process of debugging for people with little knowledge of it (such as myself), or at least some references to external resources.

**Comment by daveleroy** [comment]
The readme has been updated a few times now to include more information for each supported adpater
