### ISSUE TITLE
How to add Ruby Adapter?

### ISSUE THREAD

**Issue by fnicastri** [daveleroy/sublime_debugger#100]
Hi,
thanks for this extension!

Is there a possibility to add the ruby adapter?

Thanks

**Comment by daveleroy** [comment]
https://github.com/daveleroy/sublime_debugger/commit/2b5f0a5860027a0f2ad9b9fcd791b41a3179da57 adds support for the readapt ruby debug adapter see https://github.com/castwide/readapt

**Comment by fnicastri** [comment]
Thanks!
