### ISSUE TITLE
Inline error messages are invisible

### ISSUE THREAD

**Issue by lumnn** [daveleroy/sublime_debugger#108]
_Hi. First of all it's a great work with the plugin. Setting it up wasn't complicated especially I have used the VSCode debugger previously. Finally I don't have to switch between editors when I need debugging._

When I run debugger with "Everything" checked as a breakpoint. It stops on errors, but the error message is completely invisible.
I've tried using different themes and color schemes but it doesn't seem it's causing an issue.

![image](https://user-images.githubusercontent.com/2505114/111901789-ed0cc600-8a31-11eb-935b-13de1f190115.png)

**Comment by daveleroy** [comment]
I believe this is fixed in the st4 version but has not been released yet

**Comment by seanstrom** [comment]
I'm using Sublime Text 4 and the dialogue is hidden.

<img width="1401" alt="Screen Shot 2021-05-26 at 7 24 04 PM" src="https://user-images.githubusercontent.com/2845768/119756127-f2362900-be57-11eb-9f47-9388d60179fa.png">

**Comment by jonasmarcello** [comment]
@seanstrom : The released version on Package Control does not yet have the bug fix. Instead of installing from Package Control you can clone the master branch of the repo into your Packages folder - that will have the newest fixes and work just fine.

**Comment by anergictcell** [comment]
@seanstrom : The released version on Package Control does not yet have the bug fix. Instead of installing from Package Control you can clone the master branch of the repo into your Packages folder - that will have the newest fixes and work just fine.

**Comment by seanstrom** [comment]
@anergictcell thank you! I’ll give that a shot 👍

**Comment by seanstrom** [comment]
Okay just following up here, I cloned the latest master branch of the repo in my Packages folder, and it still has the inline error message glitch. Is there anything else that I'm suppose to do to configure this?
I will note that my packages folder was inside `~/Library/Application Support/Sublime Text 3/Packages` on macOS 10.15.7 and with Sublime build 4107.

<img width="1322" alt="Screen Shot 2021-05-27 at 9 02 14 AM" src="https://user-images.githubusercontent.com/2845768/119859680-7628f900-beca-11eb-8645-883853c66b42.png">

**Comment by anergictcell** [comment]
@seanstrom : Hm, interesting. It works fine for me:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/875703/119881481-a05fd280-bf2d-11eb-9607-c1976d5b1e56.png">


The only difference for me is that I don't have the ``Sublime Text 3``,  but just ``Sublime Text`` folder:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/875703/119881821-03516980-bf2e-11eb-9d6a-94f708bfcf49.png">

Maybe a stupid question, but did you try to uninstall the old SublimeDebugger first, restarting Sublime, then cloning the git repo, then restarting Sublime once more?

**Comment by daveleroy** [comment]
This could be unrelated the original issue. Maybe some sort of issue happening because of font-face/font-size/line-padding settings.

**Comment by daveleroy** [comment]
I'll try to update package control this weekend. It hasn't been updated since mid December.

**Comment by daveleroy** [comment]
Re-open if this is still on issue on st4
