### ISSUE TITLE
HTTP Error.

### ISSUE THREAD

**Issue by lucci06225** [daveleroy/sublime_debugger#111]
![image](https://user-images.githubusercontent.com/35951524/115546583-ce6f4880-a2d7-11eb-86a4-92829fe7dc5b.png)

I can't download the adapter. anyone help me?

**Comment by daveleroy** [comment]
Try again in an hour

This was fixed for st4 now that we are no longer downloading any extensions from the vscode marketplace

**Comment by lucci06225** [comment]
i change now into ST4 but i get this error.

![image](https://user-images.githubusercontent.com/35951524/115635520-79b2e880-a33e-11eb-9d9e-c3731fb48a10.png)

**Comment by daveleroy** [comment]
Thats just a warning. What does your configuration look like?

**Comment by lucci06225** [comment]
I wish you could fix Sublime Text 3. I found so many bugs in ST4.

**Comment by daveleroy** [comment]
I'm not working on the st3 version at all and have no plans to continue doing so.

**Comment by lucci06225** [comment]
i downloaded the adapter (chrome debug). how to add this on sublime text 3 debugger?

**Comment by lucci06225** [comment]
is now fix!!! thanks!!!
