### ISSUE TITLE
Debugger crashed when clicking "Add Configuration"

### ISSUE THREAD

**Issue by LDAP** [daveleroy/sublime_debugger#120]
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1245, in confirm_
    self.confirm(v)
  File "C:\Users\Lucas Alber\AppData\Roaming\Sublime Text\Packages\Debugger\modules\ui\input.py", line 126, in confirm
    run = self.values[value].run
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by daveleroy** [comment]
Where are you clicking this from? I feel like I have seen this before but haven't been able to reproduce it reliably.

- The "Debugger" top bar menu (which should probably be removed?)?
- The Gear menu?
- The command palette?

What does your `debugger_configurations` currently look like?

**Comment by LDAP** [comment]
Try these steps:
1. Newly installed Debugger
2. Open a file
3. Run Command: Debugger Start
4. Let debugger create a project
5. Click the play button
6. Then the ST list opens
7. Select "Add Configuration"
8. Look into the ST Console
