### ISSUE TITLE
Tooltips for debug buttons

### ISSUE THREAD

**Issue by Hunter522** [daveleroy/sublime_debugger#122]
It took me a little bit of experimenting to figure out which each of the debug toolbar buttons do. I think it would be helpful to new users or users who may not debug often to have tooltips for these buttons.

![image](https://user-images.githubusercontent.com/9222431/124801949-0c662b00-df1d-11eb-8a17-5ef0145ee53a.png)

**Comment by daveleroy** [comment]
There are now tool tips on some of the basic buttons see https://github.com/daveleroy/sublime_debugger/commit/3ae8e494adfbc2329b0ec09ccabc5a000a622724

Support for the title attribute is pretty new so you will need an up to date version of st4
