### ISSUE TITLE
Help with Debugging Rust

### ISSUE THREAD

**Issue by glubbfreund** [daveleroy/sublime_debugger#123]
Hi, 
Anybody using rust with this debugger and can tell how to set this up in windows? Do you use llvm and if yes whats your config? Tried to use llvm but either my config is wrong or i miss something because I see no output and it seems that the variables are wrong. Have to say that im totally unfamiliar with debugging without an IDE.

Thanks in advance.

**Comment by glubbfreund** [comment]
figured it out :)

**Comment by TheFoolishPupil** [comment]
@glubbfreund mind sharing your configuration?

**Comment by glubbfreund** [comment]
Sorry I had trouble with my sublime config and I'm using nvim now.

ᚺᛙᛈᛜᛁᚤᛙ ***@***.***> schrieb am Do., 12. Mai 2022, 23:28:
