### ISSUE TITLE
PHP Install Adapter 

### ISSUE THREAD

**Issue by rsiota** [daveleroy/sublime_debugger#124]
Hi there,

Thank you for the project, I look forward to start using it - it's great to have found a php gui debugger for Sublime!
I tried to install the php adapter earlier today but it was giving me a 404 error. The link to the download github page for the php vscode debugger appears to be slightly different.
The link points at: https://github.com/xdebug/vscode-php-debug/releases/download/v1.17.0/php-debug.vsix
But the link to the latest release appears to include the latest version appended at the very end, as per:
https://github.com/xdebug/vscode-php-debug/releases/download/v1.17.0/php-debug-1.17.0.vsix

![Screenshot 2021-08-04 at 22 17 13](https://user-images.githubusercontent.com/6819887/128256121-dc5bfa17-cf5a-481b-92c9-d68dd4181ecc.png)

Thank you very much!

**Comment by daveleroy** [comment]
This was fixed here https://github.com/daveleroy/sublime_debugger/commit/ce44c963ac746e4ee1fc3b4fae66a7ba060a9a65

It just has not been released to package control

**Comment by rsiota** [comment]
Thank you very much, appreciate it!

**Comment by arturolinares** [comment]
What is needed to deploy to package control?

**Comment by daveleroy** [comment]
> What is needed to deploy to package control?

I need to test some stuff and provide a way to install packages without checking for updates before releasing. I'll try to get to it this weekend.
