### ISSUE TITLE
Cannot work on Windows.

### ISSUE THREAD

**Issue by LollipopFt** [daveleroy/sublime_debugger#125]
![image](https://user-images.githubusercontent.com/62802897/128659568-7881d40e-946f-4099-a5d1-9bfe31c79984.png)
is this meant to happen?
debugger config:
![image](https://user-images.githubusercontent.com/62802897/128659614-4017eb64-de07-4358-ae69-5063e9a02dcb.png)

**Comment by daveleroy** [comment]
Add `"terminal": "console",` to your configuration and the error will go away. There are no dependencies on the python 3.8 version of sublime so the integrated terminal will not work.

**Comment by LollipopFt** [comment]
thank you! what must i set up to get what is in the screenshot?

**Comment by LollipopFt** [comment]
i can't seem to step through the code, what must i do to turn on disassembly?

**Comment by daveleroy** [comment]
> i can't seem to step through the code, what must i do to turn on disassembly?

Did you compile your program with -g so it includes debug information?

**Comment by LollipopFt** [comment]
oh, that solved the problem. thank you!
