### ISSUE TITLE
Add support for cppvsdbg/visual studio debug type

### ISSUE THREAD

**Issue by AberrantWolf** [daveleroy/sublime_debugger#126]
I have been using VSCode on Windows (for work) and I would rather use Sublime Text with sublime_debugger, but the product is built with MSBuild which (AFAICT) needs to be debugged with an MSBuild-compatible debugger.

In VSCode, this is the "cppvsdbg" type included with Microsoft's Cpp-Tools extension.

I haven't found any adapters for this debugger for Sublime. Have I missed something? Is it something I could request to be implemented (or are there relatively straightforward steps to implementing this)?

The ability to debug is pretty essential to me.

Cheers!

**Comment by daveleroy** [comment]
I'm pretty sure the license on that stuff says it can only be used with Microsoft products https://github.com/microsoft/vscode-cpptools/blob/main/RuntimeLicenses/vsdbg-LICENSE.txt

Also I am pretty sure lldb is somewhat compatible with the windows debug info format see: https://github.com/vadimcn/vscode-lldb/wiki/Windows

**Comment by AberrantWolf** [comment]
Thanks for the clarification on both counts. I'll give LLDB a shot, then. :)
