### ISSUE TITLE
Add support for (or strip) ANSI escape codes from debugger output

### ISSUE THREAD

**Issue by nicholas-ochoa** [daveleroy/sublime_debugger#127]
It looks like ANSI escape codes are unsupported - can they be stripped out / removed before display, or can support be added?

<img width="1288" alt="2021-09-19 14_59_07-node — c__git_synapse-services_apps_api_src_routes_public_multiship_package-info" src="https://user-images.githubusercontent.com/126299/133941304-27a9f301-4a75-4583-ac07-fc406b4e7e5e.png">

**Comment by daveleroy** [comment]
Some ANSI escape codes should now be working with the new console view and the rest I believe are stripped out
