### ISSUE TITLE
workspaceFolder points to the path of the project file

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#131]
I can see that `$workspaceFolder` variable is supported in the configuration and it's an alias to ST's `project_path`. I think that aliasing it to `project_path` is incorrect. At least in some cases.

`$project_path` points to the directory where the project file is saved but when using something like `ProjectManager`, the project files are saved separately from the project itself.

`$workspaceFolder`, as the name implies, should point at the project's root. I guess that would be the first folder found in `window.folders()`.

**Comment by daveleroy** [comment]
Yeah that is probably the best solution. 

I tried to alias a few of the common vscode variables so that configurations would mostly work across the two.
