### ISSUE TITLE
Schema for platform-specific configuration keys

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#134]
The configurations support platform-specific keys (`osx`, `windows`, `linux`) but `sublime-package.json` schema doesn't include those.

As far as I know, there is no ideal way of implementing that due to schema limitations.

Depending on how schema is structured, the downside are either:
 - required fields in the root are also required in platform objects (but shouldn't be)
 - there is no warning on adding unknown properties (since it's not possible to use `additionalProperties: false`

I think the latter would be preferred (and that's how VSCode does it).

**Comment by daveleroy** [comment]
Right now required fields aren't working correctly anyway... so option one works. If an adapter's schema requires specific fields LSP-json appears not to warn about them missing for some reason.

This is implemented in https://github.com/daveleroy/sublime_debugger/commit/00539219ef4d33cec4eec5acc788f1cf0f22492b
