### ISSUE TITLE
why there is no `add breakpoint command` ?

### ISSUE THREAD

**Issue by alexzanderr** [daveleroy/sublime_debugger#135]
i just want to add a breakpoint from a keybinding like `<F8>`

**Comment by daveleroy** [comment]
What is the behavior you want here? 

There is already a command for toggling a breakpoint where the current curser is if that is what you are asking for. 

```
{
	"keys": ["f8"], "command": "debugger", "args": {
		"action": "toggle_breakpoint"
	}
}
```

(There is also toggle_column_breakpoint for toggling a column breakpoint)

**Comment by alexzanderr** [comment]
thanks a lot man.
i raised this issue because i looked into the source code of this plugin i didnt find any toggle breakpoint commands.
sorry for making these cringe.

**Comment by alexzanderr** [comment]
is that command from your plugin or from sublime text?

**Comment by daveleroy** [comment]
These are from this plugin. However there is only a single debugger command called "debugger" that takes an "action" argument so they aren't all registered as individual commands.


This is all the base commands and then there are a few adapter specific ones.

https://github.com/daveleroy/sublime_debugger/blob/8f8bbd3273a77ff8b3c4fb09526bac7ef29c0d80/modules/commands.py#L98

You can see them all in the commands/context menu files as well
https://github.com/daveleroy/sublime_debugger/blob/master/Commands/Commands.sublime-commands
https://github.com/daveleroy/sublime_debugger/blob/master/Commands/Context.sublime-menu

**Comment by alexzanderr** [comment]
thanks a lot. the plugin is great.

can it debug multi process and multi threaded applications, like django or flask?

**Comment by daveleroy** [comment]
Probably not multi process python applications which isn't part of the debug adapter protocol and likely requires protocol extensions to support.

This extension `debugpy` added is not implemented and I do not have an example project where this is actually required
https://github.com/microsoft/debugpy/wiki/DAP-Client-reference#extension-to-dap
