### ISSUE TITLE
Start debugging from the command line

### ISSUE THREAD

**Issue by jrzaurin** [daveleroy/sublime_debugger#136]
Hi, 

first of all MANY thanks for this, this is amazing. 

I know that this might be duplicated with some recent issues, but I don't manage to make it work. 

my config file looks like

```
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"/Users/javier/.pyenv/versions/3.7.7/envs/tmp/bin/python\" -u \"$file\"",
		}
	],
	"folders":
	[
		{
			"path": ".",
		}
	],
	"debugger_configurations":
	[
		{
			"name": "Debug python",
			"type": "python",
			"request": "launch",
			"program": "${file}"
		},
	],
}
```

If I wanted to start debugging (i.e. reproduce the same behaviour as when I hit the `Start` button) from the command line, where should I start the keybinding 

Thanks in advance!

**Comment by jrzaurin** [comment]
The former, yeah, I want to set the breakpoint and `Start` debugging without having to click the `Start`, just with some command (such as ["super+r"]).

But do I add it within `debugger_configurations`, or just:

```
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"/Users/javier/.pyenv/versions/3.7.7/envs/tmp/bin/python\" -u \"$file\"",
		}
	],
	"folders":
	[
		{
			"path": ".",
		}
	],
	"debugger_configurations":
	[
		{
			"name": "Debug python",
			"type": "python",
			"request": "launch",
			"program": "${file}"
		},
	],
	"keys": ["super+r"],  "command": "debugger", "args": {
		"action": "start"
	}

}
```

by the way this is the look of my `project_name.sublime-project`

Cheers!

**Comment by daveleroy** [comment]
Search for `Preferences: Key Bindings` in the command palette and it should open your default keybindings they would go in there.

**Comment by jrzaurin** [comment]
thank you @daveleroy !
