### ISSUE TITLE
Adjust the size of the windows

### ISSUE THREAD

**Issue by jrzaurin** [daveleroy/sublime_debugger#137]
How one can adjust the size of the windows so that the `Debugger Console` is a bit narrower and the `Variables` window is a bit wider? 

<img width="1818" alt="Screenshot 2021-11-29 at 17 20 32" src="https://user-images.githubusercontent.com/7262383/143904649-ca14dd34-46f3-4622-82e0-54bf95629a37.png">

**Comment by daveleroy** [comment]
Currently not possible without adjusting the values in the codebase right here

https://github.com/daveleroy/sublime_debugger/blob/8f8bbd3273a77ff8b3c4fb09526bac7ef29c0d80/modules/debugger.py#L142

**Comment by jrzaurin** [comment]
Thanks!
