### ISSUE TITLE
Can not run ts-node. Attribute 'program' does not exist

### ISSUE THREAD

**Issue by Straw94** [daveleroy/sublime_debugger#138]
Cannot find the file correctly

![image](https://user-images.githubusercontent.com/32349112/143981860-401b6ec7-f830-442a-be21-5fe9763e8f71.png)

![image](https://user-images.githubusercontent.com/32349112/143982022-e9deb7a4-2436-40ab-ad9e-913eadb7b9b5.png)

**Comment by Straw94** [comment]
Can you give me an example of ts-node configuration？

Looking forward to your reply～

**Comment by daveleroy** [comment]
That error is coming from the vscode node adapter so you will probably need to consult their documentation. 

I would check the `program` attribute and make sure its actually set to the correct location.
