### ISSUE TITLE
Whenever I open sublime, it always prompts me to create a config file. Like this.

### ISSUE THREAD

**Issue by Straw94** [daveleroy/sublime_debugger#143]
![image](https://user-images.githubusercontent.com/32349112/148730646-72d7f0c4-1a88-41a7-b58b-8ddd21c93e8a.png)

**Comment by Straw94** [comment]
> You are probably opening the folder in sublime instead of the sublime project

It also not working.
'Add or Select Configuration' not allow me to choose old .sublime-project file

**Comment by daveleroy** [comment]
`.sublime-project` files are a Sublime thing you need to use `Project -> Open Project` or open Sublime with the project file.

**Comment by Straw94** [comment]
Thanks for your answer.
