### ISSUE TITLE
cwd in Task

### ISSUE THREAD

**Issue by SushilRagoonath** [daveleroy/sublime_debugger#144]
Hi, 
`	"debugger_tasks": [
		{
			"name": "Compile",
			"shell_cmd": "cmake --build build/",
			"file_regex": "$cc",
			"cwd":"${project_path}",
		},
	],`
is something like this not possible? I get this error __init__() got an unexpected keyword argument 'cwd'.
I need the build command to go off in the project root, but sublime is running it from the folder that contains the current file. e.g 
project/source instead of project. So I have to keep switching files to run the debugger

**Comment by daveleroy** [comment]
Its weirdly called `working_dir` see https://www.sublimetext.com/docs/build_systems.html

**Comment by SushilRagoonath** [comment]
Thank you! Also sorry I thought that was controlled by this project
