### ISSUE TITLE
Poor contrast in the console view

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#146]
![Screenshot 2022-01-31 at 13 23 57](https://user-images.githubusercontent.com/153197/151793349-53710591-388a-4cb1-9c1a-de42e8a947c4.png)

**Comment by daveleroy** [comment]
These just use the `region.reddish` scope without you customizing the color scheme I don't think there is much I can do here.


You can remove the background color by adding the following rule to your color scheme

```{
	"scope": "region.background.debugger",
	"background": "var(background)",
}
```

or customize the color by adding a rule for `region.reddish.debugger`

**Comment by rchl** [comment]
I don't really care so much that I would be adding overrides but I don't think it's a good idea to apply redish scope to both the text color and background color at the same time? Why not just pick one?

**Comment by daveleroy** [comment]
Probably many color schemes have bad contrast between foreground/background for `region.redish` I don't think this is really the use case `region.redish` was designed for.

It would be nice if Sublime Text generated additional scopes for foreground/background colors like `background.redish` and `foreground.redish` which only applies the color to the background/foreground.

**Comment by rchl** [comment]
Yeah, we don't really want to apply the background color in those case. At least for the case of red color, applying `error` (`source.error`) scope would make more sense visually but there is no equivalent of that for every other color.

**Comment by rchl** [comment]
I'll apply the customization you've provided after all.
This should be fixed in ST.
