### ISSUE TITLE
Java Support Yet?

### ISSUE THREAD

**Issue by bfdell** [daveleroy/sublime_debugger#147]
I saw a issue below explaining how there isn't support for java yet with this extension. Has support for java since then been added, or is there still not support for Java?

**Comment by daveleroy** [comment]
No there is a pull request open for it but its stalled out at the moment https://github.com/daveleroy/sublime_debugger/pull/106

**Comment by bfdell** [comment]
Thank you. Can you leave a comment or tag me if Java support is ever added?
