### ISSUE TITLE
update the deprecated vscode javascript debugger 

### ISSUE THREAD

**Issue by stefhol** [daveleroy/sublime_debugger#149]
Hello the new default Javascript Debugger for Vscode is [JavaScript Debugger](https://github.com/microsoft/vscode-js-debug)
the old debugger is deprecated as you can see
the vpx link is 
https://open-vsx.org/extension/ms-vscode/js-debug

**Comment by daveleroy** [comment]
There is a lot more to this than just switching over to using that.

js-debug has a bunch of none standard stuff that must be implemented. See the following tickets:
https://github.com/microsoft/vscode-js-debug/issues/969
https://github.com/microsoft/vscode-js-debug/issues/902

That extension also unfortunately does not package a usable debug adapter which means to support it will also require forking and packaging it ourself.
https://github.com/microsoft/vscode-js-debug/issues/926

**Comment by daveleroy** [comment]
Initial support for vscode-js-debug is in 0.6.4

The adapter is packaged here https://github.com/daveleroy/vscode-js-debug
