### ISSUE TITLE
Enable old view

### ISSUE THREAD

**Issue by WeetHet** [daveleroy/sublime_debugger#150]
How to enable old view of terminal console (in panel)?

**Comment by daveleroy** [comment]
It was removed since it was a massive time sink and I could never actually get it to work well enough. If minihtml ever gets more features allowing copy/paste/scrolling etc then its possible it will come back.

For most real world debugging tasks it was not very useable.

**Comment by WeetHet** [comment]
But the view you use now break split view and groups

**Comment by daveleroy** [comment]
There is a list of commands that are run to create the layout and focus the group where the view will be created in the settings so you can customize it.

If you already have a split layout the only thing you need to do is focus the group you want the console to be created in.
