### ISSUE TITLE
python debugging exception thrown on any action

### ISSUE THREAD

**Issue by ta946** [daveleroy/sublime_debugger#151]
After setting up the debugger_configuration and installing the python adapter.
Clicking on the gear icon to open settings stops working. Running the debugger only opens the debugger console and doesnt start a debugger session. And any other commands just do nothing.
I tried the configuration with VSCode and it worked normally so I checked the sublime text console and found this error being thrown every time

```
Traceback (most recent call last):
  File "C:\Users\T\AppData\Roaming\Sublime Text\Packages\Debugger\modules\core\sublime_event_loop.py", line 106, in call_exception_handler
    raise context['exception']
  File "C:\Users\T\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger_interface.py", line 150, in run
    await self.launch(no_debug=no_debug)
  File "C:\Users\T\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger_interface.py", line 197, in launch
    await self.ensure_installed(active_configurations)
  File "C:\Users\T\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger_interface.py", line 162, in ensure_installed
    if not adapter_configuration.installed_version:
  File "C:\Users\T\AppData\Roaming\Sublime Text\Packages\Debugger\modules\adapters\python.py", line 60, in installed_version
    return adapter.vscode.installed_version(self.type)
  File "C:\Users\T\AppData\Roaming\Sublime Text\Packages\Debugger\modules\adapters\adapter\vscode.py", line 83, in installed_version
    if i := info(type):
  File "C:\Users\T\AppData\Roaming\Sublime Text\Packages\Debugger\modules\adapters\adapter\vscode.py", line 66, in info
    package_json = replace_localized_placeholders(json.load(file), strings)
  File "./python3.8/json/__init__.py", line 293, in load
  File "./python3.8/encodings/cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 18263: character maps to <undefined>
```

following the error to "vscode.py", line 66
```
       type = 'python'
       path = f'{core.current_package()}/data/adapters/{type}'
	with open(f'{path}/extension/package.json') as file:
		package_json = replace_localized_placeholders(json.load(file), strings)
```

which seems to be an error with json reading the file "\Sublime Text\Packages\Debugger\data\adapters\python\extension\package.json"

I've uploaded the file and renamed the extension to .txt because github didnt allow uploading it as json.
[package.txt](https://github.com/daveleroy/sublime_debugger/files/8004936/package.txt)

I tried adding encoding='utf8' to the open(f'{path}/extension/package.json') function but that just threw another error
`UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f3a8' in position 5909: character maps to <undefined>`

I'm running windows 10 incase that makes a difference

**Comment by ta946** [comment]
managed to fix it with the following changes:

Debugger\modules\adapters\adapter\vscode.py
line 65:
```
with open(f'{path}/extension/package.json') as file:
	package_json = replace_localized_placeholders(json.load(file), strings)
```
changed to:
```
with open(f'{path}/extension/package.json', encoding='utf8') as file:
	text = file.read().encode('cp1252', errors='replace')
	package_json = replace_localized_placeholders(json.loads(text), strings)
```

1. add encoding 'utf8' to file open
2. read the file using file.read() instead of json.load(file)
3. encode to 'cp1252' because of windows, and use errors='replace' to ignore errors
4. use json.loads to load the text

**Comment by ta946** [comment]
this issue is still happening on windows with v0.6.1. thought id reopen so you can see it

**Comment by daveleroy** [comment]
Adding `with open(f'{path}/extension/package.json', encoding='utf-8') as file:` seemed to fix this for me on Windows

**Comment by ta946** [comment]
I tried that before but I get a different but similar error
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 18263: character maps to <undefined>`

idk why it works ofr you but not mine. stackoverflow says its because of emojis. python json on windows tries to decode using `cp1252` and apparently that fails for emojis, so `errors='replace'` will just ignore the emojis

**Comment by ta946** [comment]
ok i just ran the same code again to try to find a solution that isnt platform specific and it worked... 😅

and i also realized since `encode cp1252` has the `errors='replace'` option. `open()` should have it aswell

`with open(f'{path}/extension/package.json', encoding='utf8', errors='replace') as file:`

so i believe this should work for all platforms. and the errors 'replace' could be a safety net

**Comment by ta946** [comment]
fixed with latest version
