### ISSUE TITLE
evaluate variable on hover not working. found the bug

### ISSUE THREAD

**Issue by ta946** [daveleroy/sublime_debugger#152]
While debugging, if you hover over a variable nothing happens, but this is logged in the console:
```
  File ".\Debugger\start.py", line 146, in on_hover
    variable = dap.types.Variable("", response.result, response.variablesReference)
AttributeError: module 'Debugger.modules.dap' has no attribute 'types'
```
changing line 146:
```			variable = dap.types.Variable("", response.result, response.variablesReference)```
to
```			variable = dap.Variable(session, "", response.result, response.variablesReference)```
since dap.types was removed, but dap has Variable, and dap.Variable expects the first param to be session

and changing line 152:
```			component = VariableComponent(dap.Variable(session, variable))```
to
```			component = VariableComponent(variable)```
it seems to just be recreating the dap.Variable, so just pass the variable created in line 146

**Comment by daveleroy** [comment]
Should be fixed in 0.6.1
