### ISSUE TITLE
Installing Python adapter fails

### ISSUE THREAD

**Issue by mgundersonts** [daveleroy/sublime_debugger#158]
Trying to install the python adapter fails with the following message:

```
Failed to install adapter: Unable to find a suitable asset in latest release of microsoft vscode-python
```

**Comment by JunweiZheng93** [comment]
Got the same bug

**Comment by daveleroy** [comment]
This is because https://github.com/microsoft/vscode-python did not include a .vsix asset for their latest release.

See https://github.com/microsoft/vscode-python/discussions/18837

**Comment by daveleroy** [comment]
This should be fixed in the latest release but the installed version will not be the latest version.

**Comment by mgundersonts** [comment]
Appreciate you!
