### ISSUE TITLE
Directory is missing or inaccessible

### ISSUE THREAD

**Issue by DinoNuggies4665** [daveleroy/sublime_debugger#159]
Sorry if this is already an issue, I couldn't find anything similar, anyway, error:
```
Launching: \\wsl$\Ubuntu-20.04\home\dinonuggies\C++\codewars\descend\main
‌​... an error occured, unknown error

Possible cause: the working directory "\\wsl$\Ubuntu-20.04\home\dinonuggies\C++\codewars\descend" is missing or inaccessible.
```
As you can probably tell I'm using WSL to compile my C++ code, I'm assuming the debugger can't access this folder due to WSL having a weird directory, any clue for a fix?

**Comment by daveleroy** [comment]
Is that path formatted correct and points to the right location? It looks like a Windows path with `\` not a unix style path with `/`. 

The debug configuration is sent straight to the debug adapter so if the path is correct you would have to ask about it here https://github.com/vadimcn/vscode-lldb

**Comment by DinoNuggies4665** [comment]
@daveleroy Yeah I thought about it being a Windows path, but the debugger should be operating in Windows so I didn't think it a problem, I'll try looking into it.

**Comment by DinoNuggies4665** [comment]
@daveleroy Update, it's trying to run a Windows application, and I'm compiling a Linux application, is there a way to change it?

**Comment by DinoNuggies4665** [comment]
@daveleroy Ok so I compiled a Windows executable, and I have it all setup, but now it still says `Possible cause: the working directory "\\wsl$\Ubuntu-20.04\home\dinonuggies\C++\codewars\descend" is missing or inaccessible.`. If I remove the dollar sign next to `wsl$` I get `... an error occured, unable to find executable for '\\wsl\Ubuntu-20.04\home\dinonuggies\C++\codewars\descend\main.exe'`, which makes sense because I don't have a directory named that. Even if I make a directory in my C:\ drive it give me the same error, even though the path exists, even copy pasting the path in the file explorer goes to the directory.

**Comment by DinoNuggies4665** [comment]
@daveleroy Oh lord I just saw that you said to open a question at the debugger adapter GitHub, my bad!

**Comment by daveleroy** [comment]
They are going to be more knowledgeable on this. From looking at things it's not clear that WSL works with LLDB.

Its also possible you could get this to work with GDB `Debugger: Install adapter  -> gdb` which uses https://github.com/WebFreak001/code-debug

**Comment by daveleroy** [comment]
I suspect lldb/gdb would need to be running through wsl and then connected remotely via the debug adapter (I believe both the gdb/lldb adapters support remote debugging)

https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#remote-debugging
https://github.com/WebFreak001/code-debug#using-gdbserver-for-remote-debugging-gdb-only

**Comment by DinoNuggies4665** [comment]
@daveleroy Interesting, I'll try using gdb, if that doesn't work I'll try remote debugging.

**Comment by daveleroy** [comment]
I'm almost certain you need to use remote debugging using gdbserver or lldb-server (both can be used with vscode-lldb). 

The way vscode says to set this up is use vscode remotely so that the editor and all its plugins are actually running remotely in WSL see: https://code.visualstudio.com/docs/remote/wsl.

Some of the issues in vscode-lldb seem to imply that lldb will not work in WSL so I would try gdbserver see: https://github.com/vadimcn/vscode-lldb/issues/177. They are also running vscode remotely so they are not using remote debugging since the editor/plugins are running in WSL but I am pretty sure you will need to since the gdb/lldb debug adapter would be running outside of WSL and you need the debugger running in WSL.

**Comment by DinoNuggies4665** [comment]
@daveleroy I have decided the easiest answer for me is to just use gdb, because I don't want to install vscode or do anything super complicating. Thank you so much for your help, I'm sorry if I wasted your time, cheers :)
