### ISSUE TITLE
Attempting to debug rust program with LLDB

### ISSUE THREAD

**Issue by TheFoolishPupil** [daveleroy/sublime_debugger#160]
Firstly, awesome package, thanks for making it open source. I am attempting to debug a rust program with LLDB, I am trying two separate approaches, each with their own issue. The first thing I am trying to do is to is copy vscodes configuration which judging by the json works through cargo (see the first configuration in the first screenshot below). I'm notified that the `"program" property is required for launch` I figure this is probably not unexpected. I then try to set the program as asked (see second configuration in the first screenshot) and this seemingly works but I am thrown into the compiled assembly. (see second screenshot). Any help with this would be greatly appreciated. :)
![Screen Shot 2022-05-13 at 11 28 45](https://user-images.githubusercontent.com/43202406/168254695-473d4736-10a0-4bbf-9416-302ffe1964ea.png)
![Screen Shot 2022-05-13 at 11 31 15](https://user-images.githubusercontent.com/43202406/168255192-5e68ac36-acb1-4c97-ad99-67506ea79298.png)

**Comment by daveleroy** [comment]
<img width="159" alt="Screen Shot 2022-05-13 at 12 15 40 PM" src="https://user-images.githubusercontent.com/2889367/168374703-8d6a83ba-36a9-4b70-8443-c93e187067c2.png">

Should just need to toggle off Disassembly in the menu there or the command palette.

Any options that vscode-lldb implements outside the debug adapter and inside the vscode extension won't work. Presumably they fill in the `program` path automatically when using the `cargo` option.

**Comment by TheFoolishPupil** [comment]
Thanks, that did the trick. Now I will just look into how I can get it to build when I run the debugger. I imagine I'll find my answer to that in the docs for the adapter on vscode.

**Comment by daveleroy** [comment]
Building isn't part of the debug adapter protocol but you should be able to use the `pre_debug_task` field in a configuration which will be run before starting the debug adapter.

See https://github.com/daveleroy/sublime_debugger#tasks


Check out the C++ examples since they use this feature https://github.com/daveleroy/sublime_debugger/blob/master/examples/cpp/cpp.sublime-project

**Comment by TheFoolishPupil** [comment]
Thanks for the info, I'll look into it.
