### ISSUE TITLE
Readapt doesn't Work

### ISSUE THREAD

**Issue by maximyurevich** [daveleroy/sublime_debugger#162]
Ruby debugger doesn't work on Windows 11 with Ruby 3.0.4

**Comment by gobijan** [comment]
I have the same problem on my Mac unfortunately.
Readapt is installed as a global gem and also in the bundle. Somehow it still complains that readapt can't be found (no matter of the use bundler setting). Any clues? Is ist possible to give the direct shim path of readapt to the debugger?

**Comment by daveleroy** [comment]
You can now customize the path in the preferences and also possibly fixes the issue where it could not be found

https://github.com/daveleroy/sublime_debugger/commits/master
