### ISSUE TITLE
how to display Debugger Console beside to the Callstack tab

### ISSUE THREAD

**Issue by ebdm13** [daveleroy/sublime_debugger#164]
What I have:
![image](https://user-images.githubusercontent.com/60709615/176890862-65fe00b2-e08d-4474-b837-0bab34ed94e3.png)
What I would like:
![image](https://user-images.githubusercontent.com/60709615/176890325-dcfff2ab-d121-4eda-8fb5-4d042e08168d.png)

**Comment by daveleroy** [comment]
ac028b94f864a8d65c07047120202c4bd522e778 (not on package control) attempts to have a console in an output panel but the phantom rendered console is not returning since it was pretty useless for none trivial example cases when it could not be scrolled or copied.
