### ISSUE TITLE
Debugger Windows Continually Resize

### ISSUE THREAD

**Issue by ihdavids** [daveleroy/sublime_debugger#166]
- Sublime Text 4
- Windows 10
- Debugging Go
- Breakpoints don't seem to be hit but that is not what this issue is about.
- Monitor size may have to do with it. I have a curved widescreen monitor. When I maximize the window I get the following disturbing flashing of the windows:

![flashing_debugger](https://user-images.githubusercontent.com/1059210/178549487-0772b745-5cae-4c94-8919-d29d433ec57b.gif)

Notice that the window seems to continually resize?

**Comment by daveleroy** [comment]
@ihdavids can you test this with version 0.7.0?
