### ISSUE TITLE
Continuously reloading settings file

### ISSUE THREAD

**Issue by ihdavids** [daveleroy/sublime_debugger#167]
When I load up sublime I noticed that sublime seems to be reloading the settings file over and over again:

- Sublime Text 4 latest release.
- Windows 10
- Latest debugger plugin.
- Was working to debug go.

![reload_debugger_settings](https://user-images.githubusercontent.com/1059210/178551330-58993742-2a4b-4bf3-bd78-9d516f9d3b3f.gif)

**Comment by ihdavids** [comment]
It seems to be continuously rewriting: 
{
	"ui_rem_width_scale": 0.731,
}

At various sizes?

**Comment by daveleroy** [comment]
What values is it bouncing between?

`ui_rem_width_scale` adjusts the size of ui element calculations and the debugger attempt to find a value that makes the UI fit within the space given.

It does this by adjusting the `ui_rem_width_scale` up and down based on how much space is left over in the layout. The calculation appears to be bouncing back and forth between too large and too small. This calculation is done in `def _adjust_rem_width_scale(self)` if you want to adjust it.

**Comment by daveleroy** [comment]
This bouncing is causing the ui to constantly resize as you noted here https://github.com/daveleroy/sublime_debugger/issues/166

**Comment by daveleroy** [comment]
Closing since #166 is the actual issue
