### ISSUE TITLE
Trying to get Lua Debugger work

### ISSUE THREAD

**Issue by naoufalzerai** [daveleroy/sublime_debugger#168]
Hello, 

I want to run Lua debugger with [Lua-Debug ](https://marketplace.visualstudio.com/items?itemName=actboy168.lua-debug), 

```
class Lua(dap.AdapterConfiguration):

	type = 'lua-debug'
	docs = 'https://github.com/actboy168/lua-debug'

	async def start(self, log: core.Logger, configuration: dap.ConfigurationExpanded):
		
		if not shutil.which("lua"):
			raise core.Error('You must install Lua.')

		install_path = util.vscode.install_path(self.type)
		command = [
			"lua",
			f'{install_path}/extension/script/launch.lua'
		]
		return dap.StdioTransport(log, command)
....
```
When I start debugging, the program doesn't start and the debugger console shows nothing.

Best regards,

**Comment by daveleroy** [comment]
`lua launch.lua` doesn't look like it starts a debug adapter process to me.

https://github.com/actboy168/lua-debug/blob/fe1379ab71496ea5495ed1fc17fa37efb75d0343/extension/js/descriptorFactory.js#L13 they are running something called `lua-debug`/`lua-debug.exe`

**Comment by naoufalzerai** [comment]
Thanks for the reply @daveleroy , doesn't seems to work this time the console stucks, and the program doesn't starts,

```
command = [
			f'{install_path}/extension/bin/lua-debug',
		]
```
I have decided to try [another adapter](https://open-vsx.org/extension/tomblind/local-lua-debugger-vscode), here is what I did : 

```

from __future__ import annotations
from ..typecheck import *

from .import util
from .. import dap
from .. import core
import shutil

class Lua(dap.AdapterConfiguration):

	type = 'lua-local'
	docs = 'https://github.com/tomblind/local-lua-debugger-vscode'

	async def start(self, log: core.Logger, configuration: dap.ConfigurationExpanded):
		node = await util.get_and_warn_require_node(self.type, log)

		install_path = util.vscode.install_path(self.type)
		command = [
			node,
			f'{install_path}/extension/extension/debugAdapter.js'
		]
		return dap.StdioTransport(log, command)

	async def install(self, log: core.Logger):
		url = await util.openvsx.latest_release_vsix('tomblind','local-lua-debugger-vscode')
		await util.vscode.install(self.type, url, log)

	@property
	def installed_version(self):
		return util.vscode.installed_version(self.type)

	@property
	def configuration_snippets(self):
		return util.vscode.configuration_snippets(self.type)

	@property
	def configuration_schema(self):
		return util.vscode.configuration_schema(self.type)

```
```

"debugger_configurations":
	[
		{
			"type": "lua-local",
			"request": "launch",
			"name": "Test",
			"program": {
				"command": "lua"
			},
			"args": [
				"test.lua"
			],
		}
	]
```

I realy don't know what I'm missing out :confused:

**Comment by daveleroy** [comment]
Look in the protocol panel there is probably an error from whatever command you are trying to run to start the adapter

**Comment by naoufalzerai** [comment]
Yes!!! actually it was a problem with my configuration 
this one works perfectly 

```
{
			"type": "lua-local",
			"request": "launch",
			"name": "Debug",
			"cwd":"${project_path}",
			"extensionPath":"[PATH TO ADAPTER]",
			"program": {
				"lua": "lua5.3",
				"file": "test.lua"
			},
			"env": {
                 "LUA_PATH": "./?.lua"
             },
}
```
Last thing, do you know by any chance how to inject [PATH TO ADAPTER] either from the py's AdapterConfiguration or with a magic variable :open_mouth:

**Comment by daveleroy** [comment]
You can add in values to the configuration before its sent to the adapter. Here is an example https://github.com/daveleroy/sublime_debugger/blob/ac028b94f864a8d65c07047120202c4bd522e778/modules/adapters/js.py#L110

**Comment by naoufalzerai** [comment]
Works perfectly thank you !
