### ISSUE TITLE
Debug in conda environment

### ISSUE THREAD

**Issue by Okroshiashvili** [daveleroy/sublime_debugger#173]
This question could be asked several times. However, I did not find anything to solve my problem.

I'm using `Conda` sublime package to manage Python envs and my build system is also uses `Conda`.

I want to debug the code. Debugging starts successfully, but then getting `ModuleNotFoundError` meaning that during debugging sublime or the debugger uses different conda environment or even global Python installation.

Is there a solution for this problem?

P.S. I use MacOs.

**Comment by daveleroy** [comment]
You probably need to specify the python interpreter to use by adding `"python": "absolute path to interpreter" to your configuration

**Comment by Okroshiashvili** [comment]
@daveleroy  Thanks a lot. Adding  `"python": "absolute path to interpreter"` solved my problem.
