### ISSUE TITLE
Cryptic error caused by space in path

### ISSUE THREAD

**Issue by mstegmaier** [daveleroy/sublime_debugger#175]
I am not sure if this is a Sublime Text issue or an issue with Sublime Debugger but it occurs when I press the `Start` button of the Sublime Debugger:

Today I tried using the Sublime Debugger and it suddenly didn't work anymore so I tried different things and figured out the cause of the issue and how it can be worked around.

As soon as I pressed the `Start` button of the Sublime Debugger I got the following cryptic error that is of no help:
![sublime-debugger-error](https://user-images.githubusercontent.com/2619624/190440058-d5698425-2799-4036-aefd-3b0f7c27958e.png)

The cause: It turned out that the issue was caused by a space in my username ("$firstname $lastname" as created by my employer) which leads to a space in my user folder. The debugger worked just fine after moving the files to another folder (one without a space).

The workaround: When I add the following lines to the `*.sublime-project` file, the error does not occur:
```js
"folders":
	[
		{
			"path": ".",
		}
	]
```

**Comment by daveleroy** [comment]
This should be fixed
