### ISSUE TITLE
console window pops up on Windows

### ISSUE THREAD

**Issue by AmjadHD** [daveleroy/sublime_debugger#18]
Every time I run a command, the console (node) window pops up, I didn't look at the code but setting `shell=True` on windows in subprocess calls should fix it, for example:
```python
subprocess.call(cmd, shell=os.name == "nt")
```
OS: Windows 7
latest commit: 161021bd0d9c4bca5b346138e6be0d3df0706f99

**Comment by daveleroy** [comment]
I believe this was fixed sometime back
