### ISSUE TITLE
"Debugger requires a sublime project..." warning appears when any new window is created, debugger started or not.

### ISSUE THREAD

**Issue by jcowgar** [daveleroy/sublime_debugger#181]
When I first launch Sublime, no files loaded, the dialog appears stating "Debugger requires a sublime project. Would you like to create a new sublime project?"

This appeared before when I attempted to start the debugger in a window that did not have an open project. I think that is fine, but right now, even if I do something such as hit the menu entry "Preferences > Settings" a new window appears, then the dialog, then once I say click "Cancel", then my preference file split appears.

In fact, it seems even if I do File > New Window, this dialog appears.

![2022-09-26_14-18](https://user-images.githubusercontent.com/251686/192351057-8ccd9c43-c0b6-4b75-8f51-2613aa4b1a82.png)

**Comment by daveleroy** [comment]
I'll look at this tonight but its probably an issue with the startup logic which I changed in the latest version.

You can probably disable the `open_at_startup` setting until a fix is released.

**Comment by daveleroy** [comment]
This should be fixed in 0.7.2 when package control picks it up

**Comment by jcowgar** [comment]
@daveleroy, indeed it is. Thank you for the quick fix and Debugger!
