### ISSUE TITLE
Saving project file changes button sizes

### ISSUE THREAD

**Issue by mstegmaier** [daveleroy/sublime_debugger#182]
Always after saving the project file, the button sizes change. Sometimes they become smaller, sometimes they become bigger. I have attached an image illustrating them being smaller and one showing them being bigger. The buttons with text (e.g. `Console`) additionally lose their text when the buttons become smaller.

![Sublime-Debugger-Buttons](https://user-images.githubusercontent.com/2619624/193243153-7d5bfa4a-913d-4401-9e86-57ca85190aac.png)
![Sublime-Debugger-Buttons-big](https://user-images.githubusercontent.com/2619624/193243402-07e833a2-9f00-45ef-a669-5d91d3d55904.png)

**Comment by daveleroy** [comment]
This should be fixed in 0.8.0 when it hits package control

**Comment by mstegmaier** [comment]
I can confirm that this specific case is fixed now but unfortunately the fix seems to cause another issue now.
Initially the GUI started like in the small screenshot above then it has grown bigger and bigger until it reached a point where it now keeps jumping frequently between 2 sizes.

Additional notes:
- It only does happens when `Callstack` is selected, not when `Console` is selected.
- After switching from `Console` to `Callstack`, it takes a few seconds before it starts jumping
- The status bar displays `Debugger: adjusting ui 99.32%` and `Debugger: adjusting ui 100.31%` as it jumps between the 2 sizes.

**Comment by daveleroy** [comment]
@mstegmaier are all these layout issues fixed for you in the latest releases?
