### ISSUE TITLE
"We shouldn't be creating another debugger instance for this window"

### ISSUE THREAD

**Issue by carlpett** [daveleroy/sublime_debugger#184]
I've just installed this extension, and tried following along with the instructions. However, in the second step where I do "Debugger: Install adapter", there's no feedback. Checking the Console, the message "We shouldn't be creating another debugger instance for this window" is logged.
Is there a problem running the extension with multiple sublime windows open? I typically have 10 or so windows open on different projects.

If this is supposed to work, are there any hints on how to find the issue?

Running on build 4126, on Linux 5.16.19-200.fc35.x86_64. Let me know if there are other specifics that would be helpful!

**Comment by daveleroy** [comment]
Restart and then try again and scroll the console back because there is likely an error that happened the first time you open the debugger.

`We shouldn't be creating another debugger instance for this window` is triggered when you try to open the debugger a second time.

**Comment by carlpett** [comment]
Ah. Yes, a restart fixed it :+1:
