### ISSUE TITLE
Update messages on new version

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#190]
It seems like you have somewhat clever trick that you show the same `change_log.txt` file on each update but I think that's not great approach for the user as it's not really clear to what version the package was updated and what are the fixes/new features.
Also the change log is very long.

**Comment by daveleroy** [comment]
I don't see the problem showing the whole change log on update even Sublime does that and its nice to be able to see older changes as well as new ones.

Dates should probably be added for each version though.

**Comment by rchl** [comment]
Well, the Package Control upgrade messages are really designed to show changes between the previous and new version and IMO it's more useful approach for the user.

Package could have separate "Change log" entry in the menu somewhere if that's really useful to have.
