### ISSUE TITLE
Can't get Ruby on Rails debugging to work

### ISSUE THREAD

**Issue by gobijan** [daveleroy/sublime_debugger#197]
Hi, I am not sure what I'm doing wrong. I opened the Rails project (7.0.4) as a sublime project and added this configuration like this:

```
{
	"folders": [
		{
			"path": ".",
			"file_exclude_patterns": [
				".rubocop-https*"
			],
		},
	],
	"debugger_configurations": [
		{
			"type": "ruby",
			"request": "launch",
			"name": "Rails",
			"program": "${workspaceFolder}/bin/dev",
			"useBundler": true
		},
	],
}

```

Somehow it just doesn't start... The adapter is installed. Any hints I could follow?

**Comment by gobijan** [comment]
Here are some debug logs and the configuration seems to be confused, too.

![Screenshot 2023-01-03 at 16 12 01](https://user-images.githubusercontent.com/49339/210385270-faf286a2-7a35-4f48-850f-a2513c34aa0c.png)

![Screenshot 2023-01-03 at 16 12 09](https://user-images.githubusercontent.com/49339/210385297-5bcfae7c-f8ad-484e-a5c3-9865fb34d038.png)

**Comment by daveleroy** [comment]
Look in the protocol panel `Debugger: Show Protocol`

**Comment by gobijan** [comment]
Oh... Thx I thought I was seeing the logs but I wasn't 🙈 
Somehow it did not install the readapt gem correctly in Ruby 3.2.0. In Ruby 3.1.2 I can install it but in 3.2.0 I get trouble building native extensions. I filed an issue over there: https://github.com/castwide/readapt/issues/14

**Comment by daveleroy** [comment]
There is a bug here probably since if an adapter stops unexpectedly the stderr of the adapter process is supposed to be copied over to the console. 

Presumably that would have shown the issue without you having to track it down in the protocol logs.

**Comment by daveleroy** [comment]
> There is a bug here probably since if an adapter stops unexpectedly the stderr of the adapter process is supposed to be copied over to the console.
> 
> Presumably that would have shown the issue without you having to track it down in the protocol logs.

This should be fixed now
