### ISSUE TITLE
Unable to read DebuggerConsoleSyntax

### ISSUE THREAD

**Issue by sschuhmann** [daveleroy/sublime_debugger#201]
After setting up Sublime Debugger, I get the error message ¨Error loading syntax file. Unable to read ../DebuggerConsole.sublime-syntax¨ Am I missing something?

**Comment by jokervTv** [comment]
Did you find any solution?

**Comment by LDAP** [comment]
Please provide your Debugger and Sublime Text version, as well as the console log.

**Comment by daveleroy** [comment]
I believe this is fixed in the latest release with this https://github.com/daveleroy/sublime_debugger/commit/3bda3b61843901b3d2ed3c4308f5e8bbc7a4b2c8

I think `os.path.join` creates paths that sublime doesn't like in some places and not others (only on Windows?)
