### ISSUE TITLE
Java adapted raises an Unable to connect to LSP client (timed out) error

### ISSUE THREAD

**Issue by timfjord** [daveleroy/sublime_debugger#203]
I've been trying to make the Java adapter work but it always raises `Unable to connect to LSP client (timed out)` error.

It looks like there is an issue with communication with the [LSP-jdtls](https://github.com/sublimelsp/LSP-jdtls) package.

I couldn't verify this issue in `master` because this line here https://github.com/daveleroy/sublime_debugger/blob/master/modules/views/debugger.py#L10 produces an error(probably caused by this refactoring https://github.com/daveleroy/sublime_debugger/commit/68c5ed74c4aa5a5098bb92a6116624e446351ff9)

**Comment by LDAP** [comment]
Please try to reproduce with this branch https://github.com/LDAP/sublime_debugger/tree/fix/false-lsp-object and provide console and LSP logs as well as your debugger configuration, if possible.

**Comment by timfjord** [comment]
I am not able to reproduce this error with https://github.com/LDAP/sublime_debugger/tree/fix/false-lsp-object

I can also see that the debugger "communicates" successfully with the `LSP-jdtls` package
```
:: --> jdtls workspace/executeCommand(18): {'arguments': None, 'command': 'vscode.java.resolveMainClass'}
:: <<< jdtls 18: [{'mainClass': 'Solution', 'projectName': 'playground-java_24ab904a', 'filePath': '/Users/tim.masliuchenko/code/playground-java/Solution.java'}]
:: --> jdtls workspace/executeCommand(19): {'arguments': ['{"className": "Solution", "projectName": "playground-java_24ab904a", "inheritedOptions": true, "expectedOptions": {"org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures": "enabled"}}'], 'command': 'vscode.java.checkProjectSettings'}
:: <<< jdtls 19: True
```
Here is my configuration, just in case
```jsonc
{
  // "name": "Java",
  // "type": "java",
  // "request": "launch",
  // "mainClass": "Solution",
  "type": "java",
  "name": "Launch Java Program",
  "request": "launch",
  "mainClass": "",
  "modulePaths": [
    "${folder}"
  ],
  "cwd": "${folder}",
  "console": "internalConsole",
  "env": {},
  "stopOnEntry": false
}
```

**Comment by timfjord** [comment]
Great, thanks for fixing this @LDAP
