### ISSUE TITLE
Breakopint should be colored with var(--redish)

### ISSUE THREAD

**Issue by predrag-codetribe** [daveleroy/sublime_debugger#212]
Currently the breakpoints look like this:

![breakpoint](https://user-images.githubusercontent.com/115091796/221834963-dad72769-e6c1-47c2-ace7-380171d85c0f.png)

IMO, the color is too red.

<img width="775" alt="Screenshot 2023-02-28 at 11 55 51" src="https://user-images.githubusercontent.com/115091796/221835195-8d74f23e-14d9-4df7-8288-a0fd6cf8422d.png">

It would be nice if the breakpoint was coloured with `var(--redish)`, 
that way it should it will easier visaully fit with any color scheme.

**Comment by daveleroy** [comment]
This is not possible since they are images
