### ISSUE TITLE
[JS adapter] Unable to start adapter: tcp://localhost:53007 [Errno 61] Connection refused

### ISSUE THREAD

**Issue by predrag-codetribe** [daveleroy/sublime_debugger#214]
Debugger show protocol show this error:
```
-- adapter: type=node version=1.77.2
-- node: version=v16.14.2
-- socket transport process: ['/usr/local/bin/node', '/Users/codetribe/Library/Application Support/Sublime Text/Packages/Debugger/data/js/extension/src/vsDebugServer.bundle.js', '53007']
-- socket transport: localhost:53007
-> stderr !! node:internal/modules/cjs/loader:936
  throw err;
  ^
```

this path has changed and no longer exists:
https://github.com/daveleroy/sublime_debugger/blob/36c6783dc636b38abf887f3d5d64a6702cf5d52c/modules/adapters/js.py#L46

I changed it to:
```
f'{install_path}/src/vsDebugServer.js',
```
and it works.

Other info:
A similar issue exist here https://github.com/daveleroy/sublime_debugger/issues/192

**Comment by daveleroy** [comment]
This should be fixed in 0.10.1
