### ISSUE TITLE
Invalid links in update messages

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#23]
Those links are invalid:
https://github.com/daveleroy/sublime_debugger/blob/ed174017e65d7593aeeaad2954e9fe57bbd4dfdf/messages/0.1.0.txt#L4-L5
For next update you should remember to not copy the same error. Or rename the repo.

**Comment by daveleroy** [comment]
https://github.com/daveleroy/debugger should now redirect I believe
