### ISSUE TITLE
Do not scroll during debugging session

### ISSUE THREAD

**Issue by kcfnmi** [daveleroy/sublime_debugger#237]
While debugging python, while jumping thought lines it auto scrolls vertically. So the line the debugger is in stays at the center.

I would prefer to keep the scroll position and, instead, just move the highlight to the next break position.

https://github.com/daveleroy/SublimeDebugger/assets/109356759/cc938727-3298-4de4-bd8c-7ddeaa5fa19a

**Comment by daveleroy** [comment]
`view.show` is now used to show the current line
