### ISSUE TITLE
Wrong command in firefox?

### ISSUE THREAD

**Issue by kud** [daveleroy/sublime_debugger#26]
I'm not sure but, when I install the firefox plugin, I've got this:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/655838/62463595-b1ed4e80-b78a-11e9-8ad9-428a62eac06b.png">

And the firefox.json says:

```
{
	"command" : [
		"node",
		"${package}/data/debug_adapters/vscode-firefox-debug/extension/out/firefoxDebugAdapter.js"
	],
	"installation": {
		"name": "vscode-firefox-debug",
		"url": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/hbenl/vsextensions/vscode-firefox-debug/latest/vspackage",
		"format": "zip"
	}
}
```

The path in command seems to be incorrect, right?

It should be `data/debug_adapters/vscode-firefox-debug/extension/out/adapter/firefoxDebugAdapter.js`

**Comment by daveleroy** [comment]
Yeah looks like the path for running the adapter was changed in the latest version of vscode-firefox-debug

**Comment by kud** [comment]
Thank you! :)
