### ISSUE TITLE
LLDB launching issue

### ISSUE THREAD

**Issue by imciner2** [daveleroy/sublime_debugger#27]
When I try to use this package (installed via package control) with LLDB, I get the following in the console when starting the debugger:
```
Console cleared...
starting debugger...
warning: ignoring unknown option: -O command script import '/home/imcinerney/.config/sublime-text-3/Pac
warning: ignoring unknown option: -O command adapter.main.run_stdio_session()
```

There are probably several issues going on here, the first I tracked down is that calling my lldb with the command 
```
lldb -b -O command script import '/home/imcinerney/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/vscode-lldb/extension/adapter'
```
results in LLDB spitting out the help message for command. Instead, I need to call
```
lldb -b -O "command script import '/home/imcinerney/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/vscode-lldb/extension/adapter'" -O "script adapter.main.run_stdio_session()"
```
to get LLDB to actually run the script (the quotes are needed apparently).

However, when I quote those command strings in the lldb.json file like this:
```
	"command" : [
		"lldb",
		"-b",
		"-O \"command script import '${package}/data/debug_adapters/vscode-lldb/extension/adapter'\"",
		"-O \"script adapter.main.run_stdio_session()\""
	],
```
 I still get the ignoring unknown option warning in the console.

**Comment by daveleroy** [comment]
Weird. What if you do something like ```"command" : [
		"lldb",
		"-b",
		"-O",
		"command script import '${package}/data/debug_adapters/vscode-lldb/extension/adapter'",
		"-O",
		"script adapter.main.run_stdio_session()"
	],```

**Comment by imciner2** [comment]
Splitting the commands into those separate lines seems to have fixed it now.
