### ISSUE TITLE
Add ability to set environment variables for debug session

### ISSUE THREAD

**Issue by imciner2** [daveleroy/sublime_debugger#29]
It would be very useful to have the ability to set environment variables (similar to how the build system can) for the debug session.

**Comment by daveleroy** [comment]
This is part of the debug adapter configuration and isn't part of the protocol. You have to look up what configuration options are available for the adapter you are using but most of them should have some sort of `env` setting. Maybe a link to each debug adapters documentation should be added on a help section of the debugger ui or something.

**Comment by daveleroy** [comment]
https://github.com/daveleroy/sublime_debugger/blob/master/docs/setup.md has a list of most of the adapters github pages
