### ISSUE TITLE
Scroll should be on columns, not the whole window

### ISSUE THREAD

**Issue by kud** [daveleroy/sublime_debugger#31]
![Kapture 2019-08-14 at 12 10 53](https://user-images.githubusercontent.com/655838/63013485-9d950a00-be8c-11e9-97d9-c8d1919b2c4e.gif)

**Comment by daveleroy** [comment]
I don't think there is anyway to do this nicely. There isn't a way to track scrolling in real time you would have to poll the view to see if it was scrolled then revert it and move the content of the column around to get the behavior you want.

**Comment by CandyFace** [comment]
One way to do it without having to move the content but revert the UI when scrolling would be to have another column with the custom UI only, then you could dedicate first column to UI and second column to output.

Something like:
```
========================================================
Debug panel | call stack | Debugger Console | Variables|  Column 1
========================================================
| call stack output.     | console output   |          | 
|                        |                             |           
|                        |                             |  Column 2
|                        |                             |           
|                        |                             |           
|======================================================| 
```

This will disconnect the header from the content and therefore might cause confusion as to which row contains what information but it would fix the mentioned problem, not sure if that's a better compromise.
