### ISSUE TITLE
Debugger shows error when trying to run Python.

### ISSUE THREAD

**Issue by barnabasjohnthomas** [daveleroy/sublime_debugger#33]
I'm sorry but I'm a total noob at this.

Anyway, I made a custom configuration file because there weren't any in the menu. Is this expected? These are the contents of that file:

(on macOS High Sierra, trying to debug Python)

> {
> 	"folders":
> 	[
> 		{
> 			"path": "/Users/cypher/Desktop/test/test.py"
> 		}
> 	],
> 	"settings":
> 	{
> 		"debug.configurations":
> 		[
> 			{
> 				"type": "python", 
> 				"request": "launch", 
> 				"name": "Python",
> 			},
> 		]
> 	}
> }
> 

But when I try to start the debugger, it shows the following message:

> ...an error occurred, [Errno 2] No such file or directory: 'node'

And the console log:

> Starting process: ['node', '/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
> An exception occured in the main_loop
> Traceback (most recent call last):
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 25, in _exception_handler
>     raise context['exception']
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/events.py", line 127, in _run
>     self._callback(*self._args)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 110, in done
>     result = task.result()
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
>     raise self._exception
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/debugger/debugger.py", line 164, in _launch
>     self.process = Process(adapter_configuration.command, on_stdout=None, on_stderr=self.log_info)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/dap/transport.py", line 57, in __init__
>     startupinfo=startupinfo)
>   File "./python3.3/subprocess.py", line 819, in __init__
>   File "./python3.3/subprocess.py", line 1448, in _execute_child
> FileNotFoundError: [Errno 2] No such file or directory: 'node'
> 
> [Errno 2] No such file or directory: 'node'Traceback (most recent call last):
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/debugger/debugger.py", line 117, in launch
>     yield from self.launching_async
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/futures.py", line 380, in __iter__
>     yield self  # This tells Task to wait for completion.
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 304, in _wakeup
>     future.result()
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
>     raise self._exception
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 25, in _exception_handler
>     raise context['exception']
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/events.py", line 127, in _run
>     self._callback(*self._args)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 110, in done
>     result = task.result()
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
>     raise self._exception
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/debugger/debugger.py", line 164, in _launch
>     self.process = Process(adapter_configuration.command, on_stdout=None, on_stderr=self.log_info)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/dap/transport.py", line 57, in __init__
>     startupinfo=startupinfo)
>   File "./python3.3/subprocess.py", line 819, in __init__
>   File "./python3.3/subprocess.py", line 1448, in _execute_child
> FileNotFoundError: [Errno 2] No such file or directory: 'node'

Any help would be appreciated.

**Comment by RockShea** [comment]
I had the same issue: 
https://github.com/daveleroy/sublime_debugger/issues/32
you need to install Node.js

**Comment by barnabasjohnthomas** [comment]
Thanks, pal! I’m embarrassed I didn’t catch that - I didn’t check your issue before opening one because I thought it was too specific.

Dumb me. 😊

**Comment by barnabasjohnthomas** [comment]
That didn't help though - there's a new error:

> (node:19843) [DEP005] DeprecationWarning:Buffer() is deprecated due to security and

and the console shows

> Traceback (most recent call last):
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/debugger/debugger.py", line 117, in launch
>     yield from self.launching_async
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/futures.py", line 380, in __iter__
>     yield self  # This tells Task to wait for completion.
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 304, in _wakeup
>     future.result()
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/futures.py", line 285, in result
>     raise CancelledError
> concurrent.futures._base.CancelledError
> 
> Nothing to read from process, closing
> debug adapter process ended.
> Starting process: ['node', '/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
>

**Comment by barnabasjohnthomas** [comment]
Does this have something to do with my configuration file?

**Comment by RockShea** [comment]
Not sure, I see the same warning but the debugger still works for me.

**Comment by daveleroy** [comment]
You need a program in your configuration file I believe. There is some example configurations in https://github.com/daveleroy/sublime_debugger/blob/master/examples/

You probably want something like this

`"name": "Python Debug",
"type": "python",
"request": "launch",
"program": "${project_path}/test.py",
"debugOptions" : {
	"RedirectOutput": true,
}`

**Comment by barnabasjohnthomas** [comment]
Now it just prints the numbers 4 to 9.

This is the Python test code I'm trying to run:

> j = 0
> k = 0
> 
> for i in range(1,10):
> 	j = 2 * i
> 	if i > 2:
> 		k = i - 2
> 	print i

The log:

> Starting process: ['node', '/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
> An exception occured in the main_loop
> Traceback (most recent call last):
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 25, in _exception_handler
>     raise context['exception']
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/events.py", line 127, in _run
>     self._callback(*self._args)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 90, in wrapper
>     return function(*args, **kwargs)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/dap/client.py", line 393, in transport_message
>     self.recieved_msg(msg)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 90, in wrapper
>     return function(*args, **kwargs)
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/dap/client.py", line 414, in recieved_msg
>     future = self.pending_requests.pop(data['request_seq'])
> KeyError: 1
> 
> disposing Debugger
> 22136
> 22136
> Traceback (most recent call last):
>   File "/Users/cypher/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/dap/transport.py", line 107, in close
>     os.killpg(self.process.pid, signal.SIGTERM)
> ProcessLookupError: [Errno 3] No such process
> 
> Debugger Transport: closed
> Nothing to read from process, closingdebug adapter process ended.

**Comment by barnabasjohnthomas** [comment]
Hey, this just happened.

After pressing the play button, all the other buttons flash white just for a second while it's printing. And if I time it just right and hit pause then, I get a layout like the screenshot and I can step through it line by line. If I press the play button again, though, all the buttons grey out and it prints its 4-to-9 list.

**Comment by daveleroy** [comment]
There must be something up with the breakpoints or the paths that are getting sent to the debug adapter. Do you see red dots next to the lines to put breakpoints on? Like this.

<img width="396" alt="Screen Shot 2019-08-21 at 10 59 54 AM" src="https://user-images.githubusercontent.com/2889367/63455994-d7bd5900-c402-11e9-9979-887717e11d11.png">

Also make sure its running the right file. It looks like you have t2.py in both Desktop/t2.py and Desktop/T2/t2.py it looks like its running the Desktop/T2/t2.py so the breakpoints need to be placed on that file.

**Comment by barnabasjohnthomas** [comment]
Yep - that was it. When I did the whole play-pause routine, Sublime made a duplicate of the file on the desktop (instead of in the T2 folder). I deleted that duplicate and now it’s working like a charm. Thanks for everything - the plugin and the support! You’re doing great work, and kudos to you.

**Comment by barnabasjohnthomas** [comment]
Hey, before you go, could you tell me which theme you used for the demo on the main page?

**Comment by barnabasjohnthomas** [comment]
...sorry to keep on like this, but is there a way to give the program input, or is that not a feature?

**Comment by daveleroy** [comment]
The theme is DA UI but I think it was deleted https://forum.sublimetext.com/t/boxy-da-ui-theme-missing/40862

Unfortunately no you can't run the program in a terminal to gather input from stdin. 
From https://code.visualstudio.com/docs/python/debugging the adapter supports setting "console" to specify a terminal to run the program in but right now the we don't support `RunInTerminalRequest` so it won't work.

If you mean setting program args try `"args" : ["first arg", "second arg"]` that seems to be what the adapter wants

**Comment by daveleroy** [comment]
I made an issue to track terminal support https://github.com/daveleroy/sublime_debugger/issues/35

**Comment by barnabasjohnthomas** [comment]
All right - thanks again.
