### ISSUE TITLE
DeprecationWarning: Buffer()

### ISSUE THREAD

**Issue by Shinyhero36** [daveleroy/sublime_debugger#42]
When i click on the play button, i run into this problem:
![image](https://user-images.githubusercontent.com/36128190/67621780-8d49c580-f813-11e9-861a-83482f4a1c55.png)

here: is my sublime-project file:
```json
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"python\" -u \"$file\""
		}
	],
	"folders":
	[
		{
			"path": "C:\\Users\\Responsable\\Desktop\\INFO S1"
		}
	],
	"settings":
	{
		"debug.configurations":
		[
			{
				"name": "Python Debug",
				"request": "launch",
				"type": "python",
				"program": "$(file)",
			}
		]
	}
}

I did all the steps in the setup.md file

**Comment by daveleroy** [comment]
That buffer warning is from the debug adapter and isn't something that can be fixed on my end. 

I think your real issue is that $(file) isn't a valid variable. Try $file or ${file} and make sure you actually have a file open.

The python adapter doesn't give an error it just hangs if you send it "" for the program which in this case I believe is what you are doing.

**Comment by Shinyhero36** [comment]
So, I replace the () with {} and nothing. And in both case, i still had the same error. I checked that i have an open python file

**Comment by daveleroy** [comment]
That is just a warning from node that the vscode-pyhon adapter is still using Buffer() it's not the problem. 

I think I tracked down the issue and it is that the built python zip extractor is failing (for some reason it doesn't work with long paths on windows... and apparently windows default one doesn't either...) when unzipping the debug adapter some files don't get extracted.

To check if this is the issue go into the plugin folder `Debugger->data-> debug_adapters` if you see `vscode-python.zip` unzip it with something like 7zip that can handle long paths and it should start working. There will also be a partially unzipped `vscode-python` folder so you should delete first.

**Comment by Shinyhero36** [comment]
After deleting the `vscode-python` folder and extracting the `vscode-python.zip`.
I now encounter this:

```error
Error: Cannot find module 'C:\Users\Responsable\AppData\Roaming\Sublime Text 3\Packages\Debugger\data\debug_adapters\vscode-python\extension\out\client\debugger\debugAdapter\main.js'

    at Function.Module._resolveFilename (internal/modules/cjs/loa
:debugger.info der.js:794:15)

    at Function.Module._load (internal/modules/cjs/loader.js:687:27)

    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)

    at internal/main/run_main_module.js:17:11 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}


:debug adapter process ended.

Or sometimes this:
![image](https://user-images.githubusercontent.com/36128190/67639031-50510200-f8eb-11e9-9374-c59f01f793cb.png)
