### ISSUE TITLE
Javascript errors while starting debugger

### ISSUE THREAD

**Issue by sschuhmann** [daveleroy/sublime_debugger#44]
After starting the debugger (vscode-python) I get java script exceptions.

```
internal/modules/cjs/loader.js:582
    throw err;

Error: Connot find module '......\debugAdapters'main.js'
```

The debugegr module ist installed and selected. I'm using a windows 10 pc, but can test it also on linux later on.

**Comment by sschuhmann** [comment]
Are there any dependencies I have to install? I may have missed something

**Comment by sschuhmann** [comment]
Removing manually and installing the adapter again solved the issue

**Comment by daveleroy** [comment]
Hmmm. I think the issue here is the remove code for reinstalling an adapter breaks if the files its trying to delete have too long of paths on windows. 

So if you try to reinstall (or tap the install button twice) it breaks on Windows for some adapters that have very long paths
