### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by AmjadHD** [daveleroy/sublime_debugger#46]
Hi, Whenever I open a file from in project to read the code, the whole file becomes yellow (with warnings), the code is not pep8-compliant, and it really looks ugly.
You should really follow the [style guide](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwirp6ujxe_lAhXLzYUKHbqNDaEQFjAAegQIAxAB&url=https%3A%2F%2Fwww.python.org%2Fdev%2Fpeps%2Fpep-0008%2F&usg=AOvVaw0xCyNbAyoecmbLoILApdrP), this makes it a lot easier for possible contributors.
One more thing, The code contains a lot of unused imports and `from foo import *`, although this is valid code it makes the code difficult to reason about and it adds to the startup time.
maybe you should set-up a linter and a formatter for the project.
I have a [WIP](https://github.com/AmjadHD/sublime_debugger/tree/refactor) for this if you agree.

**Comment by daveleroy** [comment]
This project is a pretty rough work in progress and there is a lot more confusing and inconsistent things than formatting that need to be fixed before people can realistically contribute.

I don't think it really makes sense to put a diff on pretty much every single line to change spaces to tabs. It's why I put in the [pycodestyle] section ignoring most of the tab rules for people using it.

**Comment by AmjadHD** [comment]
Okay then.
