### ISSUE TITLE
How use this with remote xdebug(php)?

### ISSUE THREAD

**Issue by mercurykd** [daveleroy/sublime_debugger#49]
Can someone outline the steps for how to use this plugin with remote xdebug?

windows 10

**Comment by daveleroy** [comment]
Read https://github.com/daveleroy/sublime_debugger/blob/master/docs/setup.md

1. Install the php adapter
2. Read https://github.com/felixfbecker/vscode-php-debug
3. Add a configuration (CUSTOM) 
4. Modify it to be something like one of these https://github.com/felixfbecker/vscode-php-debug/blob/master/testproject/.vscode/launch.json

Its probably easiest to get things working in vsode first then copy the configuration from `.vscode/launch.json` to your sublime project settings `debug.configurations`.
