### ISSUE TITLE
0.2.1 Issues

### ISSUE THREAD

**Issue by RockShea** [daveleroy/sublime_debugger#51]
Hello - I have updated to the 0.2.1 release and have started to experience all sorts of issues, ultimately meaning the debugger is not usable 😭 

I have a remote python debugger setup which I use to debug 3DsMax, which until this release was working as expected.
When I set a breakpoint, the the gutter icon is borked:
![Screen Shot 01-06-20 at 02 38 PM](https://user-images.githubusercontent.com/14349787/71824804-49383400-3092-11ea-9531-4acb25af9573.PNG)
Hitting the break point presents a command window:
![Screen Shot 01-06-20 at 02 34 PM](https://user-images.githubusercontent.com/14349787/71824743-2dcd2900-3092-11ea-836f-d83a656f4a77.PNG)
which if left alone for 5 - 10 seconds returns to sublime at the breakpoint.
Stepping over the line presents the command window again, which takes about the same time to resolve and return to sublime.
The step buttons then grey out, but are still clickable:
![image](https://user-images.githubusercontent.com/14349787/71824888-6f5dd400-3092-11ea-8f46-f3ac711bc973.png)
Pressing step over again, the command window returns to sublime after about 15 - 20 seconds and it returns to a thread rather than remaining in the main thread.
Each consecutive step over seems to take longer and longer to process.

**Other info:**
I have Uncaught Exceptions disabled.
Here are my remote settings:
```
"debug.configurations":
[
	{
		"host": "localhost",
		"name": "Python: Remote Attach",
		"port": 3000,
		"request": "attach",
		"type": "python"
	}
]
```

This project is amazing btw, thank you for undertaking it!

**Comment by daveleroy** [comment]
Try disabling `bring_window_to_front_on_pause` if you have enabled it. I don’t think that has really ever been tested or used on Windows

**Comment by RockShea** [comment]
hey, bring_window_to_front_on_pause is disabled.

**Comment by RockShea** [comment]
Uninstalling and reinstalling a few times seems to have resolved the main issues, though the break point icons are still borked.
