### ISSUE TITLE
Output window with very small text that overlaps 

### ISSUE THREAD

**Issue by daniele-niero** [daveleroy/sublime_debugger#52]
Hi,

First of all, fantastic job. I hope this package will develop further.

I have a problem, like the title says, with the output window. 
First the text is very small, but the real issue is that sometimes line overlaps each other.

a capture to show the problem:

![2020-02-03_14h30_26](https://user-images.githubusercontent.com/967740/73657761-3fa2eb80-4693-11ea-8311-a939aa21774d.png)

I tried to change "ui_scale" in settings, but it doesn't change the size of the font.

**Comment by daveleroy** [comment]
That's annoying `ui_scale` is supposed to change the font size but must have been broken over the last few versions

The overlapping lines issue has always been a problem I wanted to get a real solution in that wasn't clipping long lines but I should probably do that for the meantime

**Comment by zimonh** [comment]
![image](https://user-images.githubusercontent.com/4648145/81931203-03641d00-95ea-11ea-9b4b-64a227b13775.png)
Would also love this fix. Or location in the code so I can fix it myself  ;)

**Comment by SimonImbrogno** [comment]
Is there any eta on getting `ui_scale` functional again? the font is just way too small for my old man eyeballs.

**Comment by ngockhanhnguyen** [comment]
Every things is perfect except

![Screenshot from 2021-02-15 11-17-54](https://user-images.githubusercontent.com/18171291/107904916-c6192b00-6f7f-11eb-81f5-30aa199eea39.png)

**Comment by daveleroy** [comment]
This should mostly be fixed
