### ISSUE TITLE
Environment not inherited from System nor Sublime (python debug)

### ISSUE THREAD

**Issue by daniele-niero** [daveleroy/sublime_debugger#53]
HI, 
I'm trying to debug a python script, but I've noticed that the debugger doesn't inherit the environment from Sublime and not even from my system (Windows 10)

For example, if I set a variable in my system, for example this:  
`MY_SYSTEM_VARIABLE = "system_variable"`,
then open a command window and input:
```
set MY_SECTION_VARIABLE=section_variable
echo %MY_SYSTEM_VARIABLE%
echo %MY_SECTION_VARIABLE%
```

I got this output:
```
system_variable
section_variable
```

Now if in the same command window I call Sublime
```
subl
```
Sublime starts and inherits the two variables (among others)

If in Sublime I create a simple python script, like this:
```
import os
print(os.environ['MY_SYSTEM_VARIABLE'])
print(os.environ['MY_SECTION_VARIABLE'])
``` 
it should give me the same result as before, however if I try to debug it, I got a KeyError, which means that the debugger doesn't see the environment, even if it is set to run the same exact python I used to run that script in Sublime.

If in the Debugger settings I set the environment again, then it works... Unfortunately things are not that simplistic like in this example and setting the proper environment again can be tricky.

**Comment by daveleroy** [comment]
This is requires passing along the sublime env to the python adapter configuration setting `env` so it's unlikely to get changed until after all my st4 change are done.

For now setting `"console": "integratedTerminal"` will cause the adapter to ask us to launch the process for them which probably means Sublime's environment will be inherited.

**Comment by daveleroy** [comment]
I believe this issue predates `debugpy` which appears to inherit the variables from its parent process now
