### ISSUE TITLE
Need help on perl debugger setup.

### ISSUE THREAD

**Issue by Shuraken007** [daveleroy/sublime_debugger#54]
Hello. I'm trying to add perl debugger to you project, but stuck halfaway.
I have founded 
https://marketplace.visualstudio.com/items?itemName=mortenhenriksen.perl-debug

I created Packages/sublime_debugger/debug_adapters/perl.json
```
{
	"command" : [
		"node",
		"${package}/data/debug_adapters/vscode-perl-debug/extension/out/perlDebug.js"
	],
	"dependencies": ["node"],
	"install": {
		"name": "vscode-perl-debug",
		"type": "vscode",
		"url": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/mortenhenriksen/vsextensions/perl-debug/0.6.3/vspackage"
	}
}
```

also added to debugger.sublime-settings
```
"adapters" : {
...
		"perl" : "${package}/debug_adapters/perl.json",
}
```

created

```		"debug.configurations":
		[
			{
				"program": "${file}",
				"type": "perl",
				"request": "launch",
				"name": "Perl Debuger",
			},
		],
```

section at project's config

when I trying to run debugger on file - getting this at standart console

```
[<sublime_debugger.modules.ui.input.InputListItem object at 0x7f5b15f79910>, <sublime_debugger.modules.ui.input.InputListItem object at 0x7f5b15f77dd0>]
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1050, in run_
    return self.run(**args)
TypeError: run() got an unexpected keyword argument 'list_1'
[<sublime_debugger.modules.ui.input.InputListItem object at 0x7f5b16002910>, <sublime_debugger.modules.ui.input.InputListItem object at 0x7f5b16003a90>]
[<sublime_debugger.modules.ui.input.InputListItem object at 0x7f5b15fac450>, <sublime_debugger.modules.ui.input.InputListItem object at 0x7f5b15fb5a10>]
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1050, in run_
    return self.run(**args)
TypeError: run() got an unexpected keyword argument 'list_7'
<sublime_debugger.modules.debugger.adapter.adapter.Adapter object at 0x7f5b15fba9d0> <sublime_debugger.modules.debugger.adapter.configuration.ConfigurationExpanded object at 0x7f5b15fbec90>
Starting process: ['node', '/home/alex/.config/sublime-text-3/Packages/sublime_debugger/data/debug_adapters/vscode-perl-debug/extension/out/perlDebug.js']
debug adapter process ended.
```

node process ends instantly

I have tried default python package - it works.
Also I installed VSCode - perl debugger works there too.
And VSCode debugger runs following on default perl debugger config:
```
cd "/home/alex/projects/sublime projects/smth/" ; env PERLDB_OPTS=RemotePort=localhost:40437 perl -d "/home/alex/projects/sublime projects/smth/test.pl"
```
default launch.json
```
    {
        "version": "0.2.0",
        "configurations": [
            {
                "type": "perl",
                "request": "launch",
                "console": "integratedTerminal",
                "exec": "C:/Perl64/bin/perl.exe",
                "execArgs": [],
                "name": "Perl Debug",
                "root": "${workspaceRoot}",
                "program": "${workspaceRoot}/${relativeFile}",
                "inc": [],
                "args": [],
                "stopOnEntry": true
            }
        ]
    }
```

So I tried to find some info - where plugin pass configuration with debugger section to node. But havn't any success. Can you give any advises - what should I debug to understand what gone wrong?

**Comment by daveleroy** [comment]
Looking at https://github.com/raix/vscode-perl-debug/blob/master/src/perlDebug.ts it doesn't appear to start the debugging session it just defines the classes to support it

I would try passing https://github.com/raix/vscode-perl-debug/blob/master/src/debugAdapter.ts which appears to start the adapter

After starting the debug adapter it communicates with the plugin over standard input/output and the configurations settings are passed from the plugin to the adapter during the` launch`/`attach` request

**Comment by Shuraken007** [comment]
![image](https://user-images.githubusercontent.com/23379636/74236450-4c9e8b00-4ce2-11ea-8836-45000898ec3b.png)
Yes, I have a bit progress.

**Comment by daveleroy** [comment]
It looks like they are patching the configuration here https://github.com/raix/vscode-perl-debug/blob/master/src/extension.ts#L176 and adding default values which is outside the of the adapter
