### ISSUE TITLE
Debugger Error

### ISSUE THREAD

**Issue by munkybuttballs** [daveleroy/sublime_debugger#55]
Hey,

I have recently got a new pc at work and am attempting to re-setup sublime.
I am getting an issue with debugger when trying to start:
![image](https://user-images.githubusercontent.com/7100563/75024008-a7797480-5490-11ea-9d22-9f8231764ca4.png)

I have managed to setup debugger twice in the previous few months with no issues.

I have tried node-v12.16.1-x64 and node-v13.9.0-x64
I have also tried most recent release 0.2.2 rolling back to 0.1.8 release as this was the most stable release for me on my last pc.

Any help would be appreciated?

**Comment by daveleroy** [comment]
I just did some testing it appears the vscode-python adapter will not run with any version of node greater than node-v12.15.0

**Comment by munkybuttballs** [comment]
Brilliant! Thank you very much for figuring that out so swiftly.
Been having to use VSCode to debug and been hating my life...

I guess it would be helpful to make this version cap more widely know?
Anyways, thanks again for the awesome plugin.
