### ISSUE TITLE
[Error 2] No such file or directory : 'node'

### ISSUE THREAD

**Issue by najeex** [daveleroy/sublime_debugger#57]
I am new to node.js or vs code. but I am trying debug my program. unfortunately, i did not understand what is going wrong. kindly help. 
**`this is the error i am facing when push debugs batton.`**
![sublime_1](https://user-images.githubusercontent.com/2714076/77193249-f48a4e00-6b03-11ea-9742-cb868e2f8087.png)
**`this is conf file`**
![sublime_2](https://user-images.githubusercontent.com/2714076/77193381-2ac7cd80-6b04-11ea-9866-c3eb29dfbdac.png)

**Comment by daveleroy** [comment]
It's saying that it can't find `node` which is required to run the gdb debug adapter. You probably just don't have it installed https://nodejs.org/en/ or its not in your path.

Also watch out for using vscode variables`${workspaceRoot}` is not going to get expanded you probably want `${project_path}`.  https://www.sublimetext.com/docs/3/build_systems.html#variables

**Comment by najeex** [comment]
I already install node.js but not package manager. and I don't how and where to add a path. i am totally new node and this plugin.

**Comment by elvis-wenhao-wu** [comment]
Same problem here, dude. But I install the package manager in the command line first. 
Sublime couldn't recognise my path variable although I've set export in the zsh profile and symlink in the /usr/local/bin...

**Comment by predragnikolic** [comment]
Try exporting the path in .profile instead of .zshrc if you are on Linux. 

You can read more here about this problem of node or npm not being found in the path:
https://github.com/sublimelsp/LSP-vue/issues/20#issuecomment-605623377

**Comment by elvis-wenhao-wu** [comment]
Thank you, predragnikolic. After doing what you've said, adding .profile to my home directory. I've met this kind of issue as well. By the way, my tech spec is macbook air 2017, macos catelina 10.15.4, zsh is my default shell. 

![image](https://user-images.githubusercontent.com/57244603/78330332-7df35300-75cf-11ea-8169-2d0e1cf14c71.png)

**Comment by daveleroy** [comment]
That looks like the same issue as https://github.com/daveleroy/sublime_debugger/issues/55 which was resolved by downgrading the version of node for vscode-python

**Comment by elvis-wenhao-wu** [comment]
Thank you so much, daveleroy. It works as I installed the node-v12.15.0. [#52](https://github.com/daveleroy/sublime_debugger/issues/52) small font overlapping issue also appears. I could bear it at the moment. But this debugger is so great. Thanks again.
