### ISSUE TITLE
Installing vscode-php adapter fails with certificate error

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#58]
Getting `Failled Finished Installing adapter: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] ... unable to get local issuer certificate`

The URL has changed maybe?

**Comment by rchl** [comment]
Actually the URL https://marketplace.visualstudio.com/_apis/public/gallery/publishers/felixfbecker/vsextensions/php-debug/latest/vspackage seems to be working so it's a problem with unhandled certficaite.

**Comment by nkoporec** [comment]
Any workarounds on how to install the PHP adapter?

**Comment by daveleroy** [comment]
Assuming you are both on dev builds then this should be fixed in 0.2.4 (as well as the unstable st4 branch)

**Comment by rchl** [comment]
WFM now. Thanks :)
