### ISSUE TITLE
Cannot install additional adapters

### ISSUE THREAD

**Issue by meengit** [daveleroy/sublime_debugger#62]
Hi @develeroy

Thank you very much for your awesome work.

I tried to add the Adobe Extend-Script Debugger, but I ended up with an `Error: Cannot find module vscode` message.

### Steps to reproduce

I created a new config file: `~/Library/Application Support/Sublime Text 3/Packages/Debugger/debug_adapters/estk.json`

Contents of `estk.json`:

```json
{
    "command" : [
        "node",
        "${package}/data/debug_adapters/extendscript-debug/extension/dist/adapter/ESDebugAdapter.js"
    ],
    "dependencies": ["node"],
    "install": {
        "name": "extendscript-debug",
        "type": "vscode",
        "url": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/adobe/vsextensions/extendscript-debug/latest/vspackage"
    }
}
```

Next, I added the debugger to my `debugger.sublime-settings – User`:

```json
{
  "open_at_startup" : false,
  "adapters" : {
    "extendscript-debug": "${package}/debug_adapters/estk.json"
  }
}
```

Then, I ran `Debugger: Install adapters` > `extendscript-debug`

The installation succeeded, and the debugger is visible, including the correct version number 1.1.2.

Finally, I did my project configuration an tried to start but ends up in:

![debugger](https://user-images.githubusercontent.com/6507355/78613857-32f66b80-786d-11ea-9774-4ad021dd47bf.png)

I know your project is a "work in progress." If you have some free minutes in your spare time, I request you to give me a short hint where I can dig into the problem because I didn't found a good entry point yet ...

**Comment by daveleroy** [comment]
There isn't really anything to be done unless you can modify the source or ask the owners to modify the source and remove the dependency on `vscode`.

All of the vscode extensions that can be `installed` are only useful because they include debug adapters as a standalone node program.

**Comment by meengit** [comment]
Thank you for your prompt answer @daveleroy. It gives me the needed context.
