### ISSUE TITLE
debugger current line vertical spacing

### ISSUE THREAD

**Issue by 8ctopus** [daveleroy/sublime_debugger#65]
I'm testing the plugin with some test php code and it appears that the current line vertical spacing is huge. Anyway to change this?

![2020-04-07_161053](https://user-images.githubusercontent.com/13252042/78662728-5f040200-78ea-11ea-8976-5e26195f8736.png)

In Visual Studio code

![2020-04-08_101447](https://user-images.githubusercontent.com/13252042/78747429-d38a7f80-7982-11ea-8bcd-22c1ccd42e91.png)

Sublime Text 3.2.2 on Windows 10

**Comment by daveleroy** [comment]
Unfortunately there isn't a great way to draw the current line without phantoms which mess with the vertical spacing

**Comment by 8ctopus** [comment]
thank you for the reply, better late than never :)
