### ISSUE TITLE
don`t save .sublime-project

### ISSUE THREAD

**Issue by safarislava** [daveleroy/sublime_debugger#67]
I downloaded this package. After I click Debugger -> Open, he asks to save .sublime-project. I agree, but he re-requests the save. This happens ad infinitum. Help me please.

**Comment by daveleroy** [comment]
It's probably mad that you have an empty project. If you manually add an empty `"debug.configurations":[]` to the project or open the debugger when a folder is open it will probably work

**Comment by safarislava** [comment]
It works! You just have to open the folder!
