### ISSUE TITLE
Overrides clicks on the gutter for normal files

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#68]
This overrides click action on the gutter for normal files, even when `Debugger` is not enabled:
https://github.com/daveleroy/sublime_debugger/blob/5f7567603ff0c7a4b3f6646e9a790234bf619818/modules/ui/events.py#L33-L36
This causes left half of the gutter to be functionally "dead" - can't select lines by clicking on that area.

**Comment by rchl** [comment]
Maybe related to #59 in that it both could be fixed by adding a view setting for an actively debugged file.

**Comment by daveleroy** [comment]
This was changed awhile back to only override clicks when a Debugger is open in the window.
