### ISSUE TITLE
Variable values not displayed when debugging Lua

### ISSUE THREAD

**Issue by petrihakkinen** [daveleroy/sublime_debugger#71]
Hi! I'm trying to setup a Lua debugger (based on existing Lua/Ravi DAP implementation). It seems to work mostly ok, but for some reason variables values are not displayed in the Variables view:

![debugger_issue1](https://user-images.githubusercontent.com/2853615/81051127-e0d75300-8ec9-11ea-9c46-e4989ec6deca.png)

x and y are numeric variables with values 1 and 2.

The debugger seems to get the values correctly, because if I click on a variable I get this:
![debugger_issue2](https://user-images.githubusercontent.com/2853615/81051414-50e5d900-8eca-11ea-934d-ac38735e230c.png)

Here's debug output from the Lua/Ravi DAP which shows the messages being passed around:
```
{"arguments": {"variablesReference": 281474976710656}, "command": "variables", "seq": 20, "type": "request"}
Request --> 'variables'
Content-Length: 245

{"type":"response","seq":25,"command":"variables","request_seq":20,"success":true,"body":{"variables":[{"name":"x","type":"number","variablesReference":0,"value":"1 (0x1)"},{"name":"y","type":"number","variablesReference":0,"value":"2 (0x2)"}]}}
Content-Length: 109
```

Variable values seem to be displayed correctly in VS Code.

Any ideas whether the issue is in the DAP or the debugger? Any pointers how I could debug this further would be appreciated.

**Comment by petrihakkinen** [comment]
I got it working with this patch to render method in variables.py:

```
value_item = ui.click(self.on_edit)[
	ui.text(name, css=css.label_secondary_padding),
	#ui.code(value) if self.syntax_highlight else ui.text(value),	<-- removed this
	ui.text(value, css=css.label_secondary_padding),	# added this
]
```

Looks like some sort of CSS / layout issue.

Note that value does not show if I remove the "css=css.label_secondary_padding" parameter from ui.text(value...).

With this workaround I don't get ui.code & syntax highlighting though. Any ideas how to fix this properly?

**Comment by daveleroy** [comment]
Weird. Is this Lua specific or is it happening for other adapters (if you have used any) for you as well?

If its Lua specific the only thing I can think of is that there are some characters in the response causing rendering issues.

`css.label_secondary_padding` changes the color and adds padding to the left and right of the text not sure why that would fix things.

**Comment by petrihakkinen** [comment]
Yes, it's super weird. I did some more testing:
1. It also happens with examples/web (Chrome javascript) 
2. The values are actually there, I can hover and click on the values. They're just not visible (or perhaps rendered with background color?) 
3. I ran the examples/web project on another computer (both Windows 10 with latest version of Sublime and debugger etc.) and it worked there.

Hmm...

**Comment by petrihakkinen** [comment]
Does the plugin cache any data that I could try to delete? I remember I tried to tweak the UI scale settings, but I restored it back to 11 afterwards, because the setting did not seem to work.

**Comment by petrihakkinen** [comment]
Problem solved! Removing Flatland theme and color scheme solved the issue (what?!?)

What color theme are you using btw.? The theme on the sublime_debugger main page looks nice.

**Comment by petrihakkinen** [comment]
Ok, I debugged this a little bit further. The theme is not the culprit here. Disabling the theme makes the text visible but it's missing syntax hightlighting, so I think disabling the theme is just a partial workaround.

For some reason the generated HTML does not contain any syntax highlighting. This is how the HTML looks like in ui.code():

span class="_1" style="line-height:0.0rem;">Array(6) [1, 2, 3, "One", "Two", "Three"]</span>

If I dump the HTML from the another machine, which works fine, the HTML looks like:

<span class="_1" style="line-height:0.0rem;"><code class="inline-highlight"><span style="color: #fb9a4b;">Array</span><span style="color: #f8f8f8;">(</span><span style="color: #b8d977;">6</span><span style="color: #f8f8f8;">)</span><span style="color: #f8f8f8;"

This is probably something stupid on my end, but I can't figure out what. Is there some setting that turns off syntax highlighting? I checked that self.syntax_highlighting is True in VariableComponent.render() so it can't be that.

Sorry to bug you with such a silly issue!

**Comment by petrihakkinen** [comment]
The problem seems to be that LayoutView fails to import a dependency:
```
try:
	from mdpopups import SublimeHighlight #type: ignore
	scheme = view.settings().get('color_scheme')
	self._highlighter = SublimeHighlight(scheme)
except ImportError as e:
	core.log_info('syntax highlighting disabled no mdpopups')
```

I'm getting an exception here:
No module named 'pygments'

On my other computer the dependency is already installed so it works.

**Comment by daveleroy** [comment]
Good catch its missing pygments in the dependencies.json which is required for mdpopups. This method of highlighting was actually removed in the st4 branch since we don't have access to dependencies yet (and it was really slow when highlighting so many snippets). The current st4 method just tries to match strings and numbers and gives them a color, it's much faster but doesn't match the color scheme or have accurate highlighting necessarily.

The other issues here is `ui.text` should be rendering something so I'll see if I can track that down by using the flatland theme

The theme is the adaptive theme with a few overrides it's hardly a complete theme or anything but it works for me.  Here is my overrides https://gist.github.com/daveleroy/3ef7eb4c7e7150c319c0e134db07fba5 it would go in `Packages/User/Adaptive.sublime-theme`

**Comment by petrihakkinen** [comment]
Nice! Fyi, we're soon going to test drive sublime debugger to debug our Lua scripts here at Remedy Entertainment (I work as a consultant for them). I think if this small issue could be fixed (just adding the dependency should be fine) it would prevent a lot of head ache from beginner Sublime users :)

The st4 approach for syntax highlighting sounds like a great idea too, especially if it's more efficient and requires fewer dependencies.

Thank you for making this stellar plugin!
