### ISSUE TITLE
Support ST3

### ISSUE THREAD

**Issue by sschuhmann** [daveleroy/sublime_debugger#72]
From what I have seen, Sublime Debugger only supports ST4 in more recent builds. Since ST4 is not released, it would be really appreciated if the plug-in would also support ST3.

Are there any features which caused the switch to ST4 without keeping support for ST3?

**Comment by daveleroy** [comment]
There is a branch for st3 https://github.com/daveleroy/sublime_debugger/commits/st3 

Moving to python 3.8 simplifies a lot of things so there really is no long term plan to continue with st3 support after st4 is released.

**Comment by naphipps** [comment]
Can this be mentioned in the README until ST4 is released? This cost me two days to fix -- all because the master branch (that package control retrieves) doesn't support the currently released version out-of-the-box. I'd just hate for new users to be deterred just because of something like this.

**Comment by daveleroy** [comment]
I added a note in the clone section and fixed the version check so it actually issues a readable error.

Package control should be installing a compatible version unless you are explicitly adding this repository in which case you are going to get whatever is on the master branch which has generally not been tested.
