### ISSUE TITLE
Unable to get it to detect delve in my path

### ISSUE THREAD

**Issue by TheSecEng** [daveleroy/sublime_debugger#73]
I've tried lots of settings, and I can't seem to get it to detect that I do have delve installed. Any ideas on what might be causing this?

<img width="489" alt="2020-05-15_13-28-06" src="https://user-images.githubusercontent.com/32599364/82078940-ff9ace00-96af-11ea-8689-195ef13e21f6.png">

<img width="703" alt="image" src="https://user-images.githubusercontent.com/32599364/82079111-4be60e00-96b0-11ea-9e0c-adb1e6cfa3ac.png">

**Comment by daveleroy** [comment]
You can probably set `dlvToolPath` in the configuration to point to it

**Comment by TheSecEng** [comment]
Thanks. Not sure how I overlook this setting

**Comment by daveleroy** [comment]
I don't think its documented. It looks like they have switched over to using `vscode. DebugConfigurationProvider` to patch in some configuration settings which happens outside the debug adapter unfortunately.

https://github.com/microsoft/vscode-go/blob/master/src/goDebugConfiguration.ts

**Comment by TheSecEng** [comment]
Problem solved.

**Comment by daveleroy** [comment]
I added a few improvements in https://github.com/daveleroy/sublime_debugger/commit/15a40a0a323f51e5b3821e1160a0787b3dae9f19

`dlvToolPath` is now resolved to the setting `go.dlv` if set otherwise it will use `shutil.which`
