### ISSUE TITLE
use debugpy directly for debugging python code

### ISSUE THREAD

**Issue by randy3k** [daveleroy/sublime_debugger#75]
Any chance to use [debugpy](https://github.com/microsoft/debugpy) to debug directly instead of relying on nodejs?

**Comment by daveleroy** [comment]
It looks like its packaged in vscode-python but still in the experimental phase.

If you want to try it out I think you can update the command arguments in https://github.com/daveleroy/sublime_debugger/blob/master/modules/debugger/adapters/python.py

To something like 

``` python
command = [
	'python3',
	f'{install_path}/extension/pythonFiles/lib/python/debugpy/wheels/debugpy/adapter',
]
```

**Comment by daveleroy** [comment]
It would be nice to stop using the node adapter since it is not compatible with the latest versions of node

**Comment by randy3k** [comment]
Thanks, I confirm that it is working. Though it seems that `debugOptions` is now a list, so I have to do

```
		"debug.configurations":
		[
			{
				"name": "Python Debug",
				"type": "python",
				"request": "launch",
				"program": "${project_path}/main.py",
				"debugOptions" : []
			},
		]
```

**Comment by daveleroy** [comment]
This can now be enabled with the setting `python.experimental_debugpy_adapter`. debugpy is started with `python3` which I don't think will work on Windows and it should be customizable.

**Comment by daveleroy** [comment]
`debugpy` is now the only supported python adapter since vscode-python has removed ptvsd
