### ISSUE TITLE
`ui_scale` is incorrectly being applied to debug window.

### ISSUE THREAD

**Issue by SimonImbrogno** [daveleroy/sublime_debugger#77]
I was fiddling around with the settings trying to increase the `ui_scale` but the setting didn't seem to be having an effect. I started poking around in the source to see where it was being set and tried hard-coding it to a large value.

 i.e I changed:  `modules/debugger/debugger.py:320`
from `self.panel.ui_scale = get_setting(self.panel.phantom_view(), 'ui_scale', 12)`
to `self.panel.ui_scale = 20`

and this was the result: 
![image](https://user-images.githubusercontent.com/28269139/85930154-a2359780-b87f-11ea-894e-ce16eb7ed383.png)

It looks like the size is only applying to the top level container and not cascading down to the contents? Also, I'm assuming that text entry isn't meant to be enabled on the background container 👀

**Comment by daveleroy** [comment]
This was fixed in the st4 release
