### ISSUE TITLE
Debugger: Install Adapters > vscode-lldb installs adapter at incorrect path.

### ISSUE THREAD

**Issue by SimonImbrogno** [daveleroy/sublime_debugger#78]
After installation of the lldb adapter (via the command palette), Debugger is expecting to find it at an incorrect location:

Expected: `debug_adapters/vscode-lib/extension/adaptor2/codelldb`
Actual: `debug_adapters/vscode-lib/extension/adaptor/codelldb`

**Comment by daveleroy** [comment]
This was fixed in https://github.com/daveleroy/sublime_debugger/commit/5dbbb5651aab640de1a668543eab8e0f2a6a5378
