### ISSUE TITLE
Linux Mint 20 -  Python debugger doesn't find python

### ISSUE THREAD

**Issue by Sawrz** [daveleroy/sublime_debugger#83]
Hi,
another strange issue:
migrating everything to another machine, which runs Linux Mint 20, I got the error "No such file or directory: 'python'". 

The reason for that, there is no 'python' command on Mint, only python3. I tried to add an alias to the `.bashrc` on my system, but it doesn't work at all even though it works within the console. 

The only way to get it working was to change the `command` to `"python3"`within the adapter. I fear that gets overridden as soon as the adapter updates. Is there a more elegant way of doing that?

**Comment by daveleroy** [comment]
The master branch which is for st4 moved over to having the adapter configurations in code so things like this can easily fixed by checking if `python3` is on the path before falling back to `python`

I believe your path issue is probably related to this https://github.com/sublimelsp/LSP-vue/issues/20#issuecomment-605623377. However, your solution is probably fine for now even though it will be overriden on updates.

**Comment by Sawrz** [comment]
Ok! However, I'm not sure about this. Maybe I don't get it right, but as far as I understand, they have an issue with asdf, which creates another Python instance/installation for itself. 
Their solution is to add the init script to the `.bashrc`, since it seems sublime doesn't read `.zshrc`. My system neither uses zsh nor uses asdf. It's more about the binary `python` doesn't exist, but only `python3` or `python2`. So, I tried to fix that issue with an alias in the `.bashrc`, but the problem still exists. 

However, there is a robust and easy fix for that (should have thought of this earlier):
Create a symbolic link of the `python3` binary and call the link `python`. In other words
```
sudo ln -s /usr/bin/python3 /usr/bin/python
```
Now, I don't need to touch the adapter file at all, since the binary `python` exists for the OS.

Nonetheless, I'm glad in ST4 things are much easier. Thanks for this phenomenal plugin. Couldn't live without ist!

**Comment by daveleroy** [comment]
Sorry I didn't read your issue close enough you did explicitly mention you added it to `.bashrc` in which case I would think Sublime should be picking it up on restart.

**Comment by rchl** [comment]
It needs to be in `.profile`, not .bashrc.
And re-login is required after adding.
