### ISSUE TITLE
how to choose Python interpreter of VScode-Python under Sublime_debugger

### ISSUE THREAD

**Issue by fromtoronto77** [daveleroy/sublime_debugger#84]
I have both Python 2 and 3 in sublime. I installed sublime_debugger and chose VScode Python as debugger successfully. Although my sublime build-system is under Python 3.7, the debugger only uses Python 2.7 for the runpy.py. Does this inconsistency matter? How to choose Python 3.7 as python interpreter for my sublime_debugger? Thanks a lot.

**Comment by daveleroy** [comment]
I believe you can add `"python": "path to python interpreter"` to your configuration to change it.

**Comment by fromtoronto77** [comment]
Thanks for reply. In which file to add this configuration is my question. I tried this in the following files: "debugger-setting", settings.json  in .vscode, Sublime Text 3/Packages/Debugger/data/debug_adapters/vscode-python/extension/pythonFiles/.env, none works.

**Comment by daveleroy** [comment]
In your sublime project file you have a debug configuration it should look something like the following.
```
{
	"name": "Python",
	"type": "python",
	"request": "launch",
	"program": "${project_path}/test.py",
	"python": "python3"
}
```

**Comment by fromtoronto77** [comment]
thumb up. works now
