### ISSUE TITLE
HTTP 429 Error When Installing Go Adapter

### ISSUE THREAD

**Issue by nickhstr** [daveleroy/sublime_debugger#86]
When attempting to install the `go` adapter, I'm greeted with an HTTP 429 error, indicating the "user" for the Debugger package has made too many requests for `https://marketplace.visualstudio.com/_apis/public/gallery/publishers/golang/vsextensions/Go/latest/vspackage`.

**Comment by nickhstr** [comment]
I've experience the same issue for the `node` adapter as well, however the `lldb` adapter installs without issue.
I guess that implies the `node` and `go` adapters are more popular.

**Comment by ryanpcmcquen** [comment]
Same issue with the Firefox adapter, perhaps there were all renamed?

**Comment by ryanpcmcquen** [comment]
@daveleroy, do we just need to update the links for those?

**Comment by ryanpcmcquen** [comment]
@daveleroy, looks like the format may have changed ... this seems to work though:
```https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/node-debug2/latest/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage```

**Comment by ryanpcmcquen** [comment]
Although, the link in the code works as well ...

**Comment by ryanpcmcquen** [comment]
I did a `Package Control: Upgrade/Overwrite All Packages` and now everything works!

**Comment by daveleroy** [comment]
429 is probably because there is no session tokens or anything added to the requests so they end up getting rate limited. lldb is downloaded from github so doesn't have the same problem

**Comment by daveleroy** [comment]
![Screen Shot 2020-09-08 at 4 42 15 PM](https://user-images.githubusercontent.com/2889367/92537945-429a2780-f1f2-11ea-9469-4bc30efe7dc3.png)

It appears VSCode seems to add some hardcoded user-id on their request
