### ISSUE TITLE
Go Extension - Updated Debug Script Directory

### ISSUE THREAD

**Issue by nickhstr** [daveleroy/sublime_debugger#87]
When attempting to start a Go debug session, I ran into this:
```
Error: Cannot find module '/Users/username/Library/Application Support/Sublime Text/Packages/Debugger/data/adapters/go/extension/out/src/debugAdapter/goDebug.js'
```

Upon inspection of the latest file structure for the Go extension, I found that there is no longer a `go/extension/out` directory. Instead, there is now a `go/extension/dist` directory, holding what I imagine is the new replacement for `goDebug.js`: `debugAdapter.js`.

**Comment by daveleroy** [comment]
This was fixed in https://github.com/daveleroy/sublime_debugger/commit/c00a04b73188eeb0164d01b9e2aa550b39f2a448
