### ISSUE TITLE
UI and text are bigger than usuall?

### ISSUE THREAD

**Issue by predragnikolic** [daveleroy/sublime_debugger#88]
Are the text and icons suppose to be this big in the panel?  :)

![image](https://user-images.githubusercontent.com/22029477/89741946-d95db200-da95-11ea-8a29-d65da088af22.png)

I Installed DAP from Package Control,
ST version 4081

**Comment by daveleroy** [comment]
Definitely not. All the width calculations must be off as well since the line numbers aren't right aligned.

**Comment by daveleroy** [comment]
Apparently the character width calculation just doesn't work on windows. I tagged a new version that uses an approximation for now.

**Comment by predragnikolic** [comment]
BTW, I am on Linux, an the text/icons are still big. I will also investigate why.

Yesterday on [discord](https://discord.com/channels/280102180189634562/280157083356233728/742058305970765844) I noticed that some people reported bigger font rendering, too.
I tried installing builds from 4070 till 4081 just to see if this issue was introduced recently. but I see the same big text in each build :)

**Comment by predragnikolic** [comment]
When I open the sublime console and these are my font_size and em_width
```
>>> view.settings().get('font_size')
10
>>> view.em_width()
8.0
```

I put a print line in the debugger [here](https://github.com/daveleroy/sublime_debugger/commit/6cc89857ba3cf6790e0162974e0d0fd7e330c28f#diff-8fdcf0685f204f2a2c72762b743f64ffR157).
Here are the logs:
```
em_width 9.0 font_size 11 em_width/font_size= 0.8181818181818182
```

font_size and em_width are not the same

For now I hard-coded the `rem_width_scale = 0.62` to suit my needs. 
if I conclude something I will let you know.

**Comment by daveleroy** [comment]
I looked into this a bit more and setup a linux vm and am seeing basically the same issue.

It appears that changing the font_size of the output panel changes the the size of the font internally but it doesn't actually match the font size that was set (its slightly bigger) and the rem_width returned is based on that internal font size not the setting.

https://github.com/daveleroy/sublime_debugger/commit/4de170a30a1b18d1f184fd7d31ef13833cf87616 addresses the font size issue by just setting the font size on the phantom directly which seems to work but means there is no way to calculate the rem_width_scale correctly. For me It appears that the rem_width scale is ~0.625 on linux and ~0.55 on windows for all font sizes (not sure if that is going to be the case for everyone and on mac the rem_width scale is different for each font size).

https://github.com/daveleroy/sublime_debugger/commit/e83bace56d5847475b85a5c64f88bbd51608e3de matches up the ui_scale setting to match the platform default font size but if the ui is still too large you can always change it to a lower value.

**Comment by predragnikolic** [comment]
Thanks for taking the time to fix this,
the issue is resolved.
