### ISSUE TITLE
How do I configure my debugger adapter?

### ISSUE THREAD

**Issue by rwols** [daveleroy/sublime_debugger#92]
There are these "preconfigured" adapters that I can install. I would instead like to configure my own adapter. In my case, I have lldb-vscode-12 installed via the apt repository at apt.llvm.org.

**Comment by daveleroy** [comment]
It's not really setup to easily allow that right now but you can create a simple plugin with something like the following (if the transport is over stdio). You also need a .python-version file with 3.8 so its gets run in the correct plugin-host.

```
from Debugger.modules.debugger import adapter

class LLDBVSCode(adapter.AdapterConfiguration):
	@property
	def type(self):
		return "lldb-vscode"

	async def start(self, log, configuration):
		command = ['lldb-vscode']
		return adapter.StdioTransport(log, command)

	@property
	def installed_version(self):
		return '0.0'
```

https://github.com/daveleroy/sublime_debugger/tree/master/modules/debugger/adapters has some more advanced configurations.

Just a warning the interface is likely to change in the near future.

**Comment by rwols** [comment]
The plugin picks up my adapter class, but after playing with it for a while I can only get this in the debugger console:

```
error: ld-2.27.so 0x7fffffff0005c587: adding range [0x1469a-0x1470a) which has a base that is less than the function's low P
C 0x14e10. Please file a bug and attach the file at the start of this error message
```

this is printed three more times with different memory addresses.

configuration in my .sublime-project:

```
	"debugger_configurations" : [
		{
			"name" : "launch tests",
			"request" : "launch",
			"type" : "lldb-12",
			"program": "${folder}/test",
		}
	]
```

I have placed the adapter class in Packages/User/lldb.py

```python
from Debugger.modules.debugger import adapter


class Lldb12(adapter.AdapterConfiguration):
	@property
	def type(self):
		return "lldb-12"

	async def start(self, log, configuration):
		return adapter.StdioTransport(log, ["lldb-vscode-12"])

	@property
	def installed_version(self):
		return '0.0'
```

**Comment by rwols** [comment]
Note that this executable does exist:

```
raoul@raoul-Latitude-5500 ~ [127]> lldb-vscode-12 --help
OVERVIEW: LLDB VSCode

USAGE: lldb-vscode-12 options

OPTIONS:
  -g                  Alias for --wait-for-debugger
  --help              Prints out the usage information for the LLDB VSCode tool.
  -h                  Alias for --help
  --port <port>       Communicate with the lldb-vscode tool over the defined port.
  -p <value>          Alias for --port
  --wait-for-debugger Pause the program at startup.

EXAMPLES:
  The debug adapter can be started in two modes.

  Running lldb-vscode without any arguments will start communicating with the
  parent over stdio. Passing a port number causes lldb-vscode to start listening
  for connections on that port.

    lldb-vscode -p <port>

  Passing --wait-for-debugger will pause the process at startup and wait for a
  debugger to attach to the process.

    lldb-vscode -g
```

**Comment by rwols** [comment]
Ah, I can also reproduce that `ld` error when running the file with `lldb` in the terminal, so we're getting somewhere :)

**Comment by daveleroy** [comment]
I think the only thing I suggest is make sure you are using the -g flag and check that any debug information that is generated is actually new.

You might want to try with llvm 11 (stable) unless there is a reason use the dev branch of llvm.

**Comment by rwols** [comment]
I got it to work in the end. Turns out it runs the target process just fine.

This is definitely a cool package, but I have some thoughts about UX improvements. If you like, I can open a new issue for it.

**Comment by daveleroy** [comment]
Awesome!

Yeah go ahead and open an issue for them.
