### ISSUE TITLE
how do I configure to make this work?

### ISSUE THREAD

**Issue by drYukiWang** [daveleroy/sublime_debugger#93]
Hi, I am using conda build system where there are multiple conda environments that I can switch in my work.

I am following this https://github.com/daveleroy/sublime_debugger/blob/master/docs/setup.md and stuck at the add configuration step.

1. which file / files should I edit? do I need to have a configuration file per project? assuming i need to create sublime projects first? How to setup global configuration? - I am only using conda environments at the moment

2. What is the simplest way to set up: add breakpoints, run the program step by step, etc., step in/out of the breakpoints?

Thank you.

**Comment by daveleroy** [comment]
I do not really know anything about conda but here is a python example project you can take a look at https://github.com/daveleroy/sublime_debugger/tree/master/examples/python and run. The configuration is in the .sublime_project file open the project and open the debugger and hit the play button. Breakpoints can be set by clicking on the gutter.

You have to use a sublime project to configure a debugger there is no global configurations.
