### ISSUE TITLE
Installing python adaptor causes HTTP error 429

### ISSUE THREAD

**Issue by RockShea** [daveleroy/sublime_debugger#95]
Hello - I am attempting to get the latest adaptor installed but I am getting this response in Sublime:
![image](https://user-images.githubusercontent.com/14349787/99059593-b6600400-2596-11eb-99d4-264e462e5d10.png)
The error message is:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429#:~:text=The%20HTTP%20429%20Too%20Many,before%20making%20a%20new%20request.

When I go to the web address in chrome, it gives me this:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/latest/vspackage
![image](https://user-images.githubusercontent.com/14349787/99059684-d1cb0f00-2596-11eb-80f1-3743f1426d10.png)

I have tested this on multiple PCs - not sure how to proceed?

**Comment by daveleroy** [comment]
Wait until the quota resets. I believe it resets every hour so you should try again

**Comment by daveleroy** [comment]
This shouldn't be a problem anymore
