### ISSUE TITLE
sublime-package schema?

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#96]
I was excited to see this:
https://github.com/daveleroy/sublime_debugger/blob/6f20c92dc8c6c20842ffcd52bdcee010a2c3ffd2/docs/change_log.txt#L10
but I can't see any `sublime-package.json` file in the repo.

**Comment by daveleroy** [comment]
It is generated when an adapter installed

**Comment by rchl** [comment]
I see. But then it is not picked up by LSP-json until ST is restarted I guess? Unless you start with an empty object and then just modify it?

**Comment by daveleroy** [comment]
Ah I probably never tested without the `sublime-package.json` already there. I guess I need to create an empty one for the system to pick up any modifications.

**Comment by rchl** [comment]
Yes, I think you would need to start with the file present and empty object `{}` since LSP-json only scans for files at init.

**Comment by daveleroy** [comment]
Yeah just checked that seems to do the trick
