### ISSUE TITLE
Missing descriptions in schema

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#97]
The schema fields don't have proper descriptions. Tried on the node adapter:

![Screenshot 2020-11-13 at 15 46 22](https://user-images.githubusercontent.com/153197/99084703-95fc6d80-25c7-11eb-94a1-4ee8a4d2d10e.png)

**Comment by daveleroy** [comment]
These are generated from the package.json file. Some of those are localized and that is not currently implemented.

**Comment by daveleroy** [comment]
This should now be fixed
