### ISSUE TITLE
Debugger windows not in a row

### ISSUE THREAD

**Issue by marcoSven** [daveleroy/sublime_debugger#99]
The 3 debugger windows are stacked. I assume there is a setting I am not aware of.

I would like my layout to look like this https://github.com/daveleroy/sublime_debugger/raw/master/docs/images/basic.png

ST4 on a Mac

**Comment by daveleroy** [comment]
Do you have a screenshot of what it looks like right now? There isn't any layout settings besides `ui_scale`.

**Comment by marcoSven** [comment]
<img width="1223" alt="Screen Shot 2020-11-29 at 9 06 55 PM" src="https://user-images.githubusercontent.com/3860298/100571057-0cb38f00-3287-11eb-97df-006e803d08da.png">
<img width="1248" alt="Screen Shot 2020-11-29 at 9 07 14 PM" src="https://user-images.githubusercontent.com/3860298/100571062-0de4bc00-3287-11eb-9846-bb2b165b9113.png">
<img width="1242" alt="Screen Shot 2020-11-29 at 9 07 39 PM" src="https://user-images.githubusercontent.com/3860298/100571064-0de4bc00-3287-11eb-9062-3fb669dce707.png">

**Comment by marcoSven** [comment]
Changing the ui_scale to 20 from the default 10 fixes the issue. Though the icons are blurry, and the font is obviously very large at that size :).

**Comment by daveleroy** [comment]
Something is probably wrong with the character width calculations here https://github.com/daveleroy/sublime_debugger/blob/3fb4d231fe6459727000f6635e38eb88f88335f9/modules/ui/layout_view.py#L158

If you run the following in the sublime console what values do you get?
`window.find_output_panel('Debugger').settings().get('font_size')`
`window.find_output_panel('Debugger').em_width()`

**Comment by daveleroy** [comment]
Its probably has something to do with the font being used. What are your font settings?

**Comment by marcoSven** [comment]
> window.find_output_panel('Debugger').settings().get('font_size')


20

> window.find_output_panel('Debugger').em_width()

12.499999999999998


> What are your font settings?

"font_face": "Operator Mono SSm",
"font_size": 12,

**Comment by daveleroy** [comment]
I introduced a separate font setting just for the debugger panel just now in 41bf0eb50818a4181e72e3786fc0d09fc83f0628  but if removing the font face didn't fix the issue I wouldn't think this change would fix it either

**Comment by marcoSven** [comment]
Thank you I will try when I get the update and report back.

**Comment by marcoSven** [comment]
Yes, 41bf0eb did not fix the issue. 
What fixed the issue was removing the "wrap_width" attribute in my Packages/User/Preferences.sublime-settings.

**Comment by daveleroy** [comment]
Thanks for reporting back.

https://github.com/daveleroy/sublime_debugger/commit/34eca864d7b4aed89a362526883020721f20f5eb should resolve the issue with wrap_width when its released

**Comment by devnix** [comment]
I'm suffering this too, I have no idea when it started to happen but combined with the scroll is a huge pain in the back.
![image](https://user-images.githubusercontent.com/1777519/113136925-358f6500-9224-11eb-936f-697c4904d152.png)

Apart from that, this project adds so much value to Sublime Text that I will never ever install VSCode again <3

**Comment by daveleroy** [comment]
This layout issue should be fixed
